### ISSUE TITLE
VDK Windows support for vdk-kerberos-auth

### ISSUE THREAD

**Issue by ivakoleva** [vmware/versatile-data-kit#1183]
**What is the feature request? What problem does it solve?**
Installing and using vdk with vdk-kerberos-auth on windows currently does not work  

**Suggested solution**
Troubleshoot to fix issues with installing/running VDK on Windows platform. Introduce automated operability verification, to continuously guarantee support.

**Additional context**
vdk-kerberos-auth dependencies may be a point of concern;

**Comment by tozka** [comment]
What is the issue? Can you provide steps to reproduce? VDK (vdk-core or quickstart-vdk) supports windows. 

It's possible that a single plugin of VDK doesn't work on windows. But vdk-kerberos-auth is just one plugin. The ticket should be about the plugin if so.

**Comment by ivakoleva** [comment]
> What is the issue? Can you provide steps to reproduce? VDK (vdk-core or quickstart-vdk) supports windows.

There is no Windows support, for example https://github.com/vmware/versatile-data-kit/issues/871, or feedback about vdk-kerberos-auth plugin usages attempted by Windows users, show there are show-stoppers for using VDK on Windows.
To answer the question "what are the show-stoppers exactly", it is to be investigated in the scope of the current one.

The VDK official Windows support seems a presumption - until we have a continuous delivery that ensures the Windows support. Such a support includes versatile-data-kit project code as well as dependencies, transitive dependencies and their upgrades.

It is also true, that VDK users are recommended currently to use some type of virtualisation in case of running Windows natively, in order to use VDK.

**Comment by tozka** [comment]
> There is no Windows support, for example https://github.com/vmware/versatile-data-kit/issues/871, or feedback about vdk-kerberos-auth plugin usages attempted by Windows users, show there are show-stoppers for using VDK on Windows

There are people using vdk (quickstart-vdk) on Windows. I just install it and created and run and deployed a job. It's misleading to say it's not working.

> The VDK official Windows support seems a presumption - until we have a continuous delivery that ensures the Windows support

That is true. We should add tests on windows. Though the fact is if we use only pure-python libraries (without native bindings) , that would not be a problem. In vdk-kerberos-auth we need native kerberos library which is what causes issue there. 

So we need 2 things: 
A) Automated tests to run on windows (probably for vdk-core and/or quickstart-vdk) 
B) We need to fix vdk-kerberos-auth 

Which of those issues is this ticket aiming to cover ? We need to be specific in the ticket.

**Comment by tozka** [comment]
I've renamed the ticket to reflect B) - We need to fix vdk-kerberos-auth to support windows

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
