### ISSUE TITLE
[vdk-server] kind error - resource mapping not found for name: "vdk-cockroachdb-budget"

### ISSUE THREAD

**Issue by zverulacis** [vmware/versatile-data-kit#1187]
**Describe the bug**
When I'm installing vdk server on Windows WSL 2 following the instructions in [wiki](https://github.com/vmware/versatile-data-kit/wiki/Installation#install-versatile-data-kit-control-service)
`vdk server --install` command fails with an error: 

```
v-error: Stderr output: Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "vdk-cockroachdb-budget" namespace: "default" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
error: ensure CRDs are installed first
```

**Steps To Reproduce**
1. Install and set up WSL 
2. Install helm, docker, kind
3. run `vdk server --install`

Full output: 
```
vdk server --install
Starting installation of Versatile Data Kit Control Service (this may take several minutes)
Creating Kind cluster "vdk"...
Kind cluster "vdk" created
Creating Docker registry container "vdk-docker-registry"...
Docker registry container "vdk-docker-registry" created
Creating Git server container "vdk-git-server"...
Git server container "vdk-git-server" created
Git server configured successfully
Installing prerequisites...
Done
Installing Control Service in Kind cluster...
-error: Stderr output: Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "vdk-cockroachdb-budget" namespace: "default" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
error: ensure CRDs are installed first
```

**Expected behavior**
Installation should complete successfully

**Version  (please complete the following information):**
 - OS: Windows
 - WSL version 2
 - VDK Version

```
Versatile Data Kit (VDK)
Version: 0.3.572339461
Build details: RELEASE_VERSION=0.3.572339461, BUILD_DATE=Fri Jun 24 14:57:27 UTC 2022, BUILD_MACHINE_INFO=Linux runner-opyxurxq-project-28359933-concurrent-0wcg7j 5.4.181-99.354.amzn2.x86_64 #1 SMP Wed Mar 2 18:50:46 UTC 2022 x86_64 GNU/Linux, GITLAB_CI_JOB_ID=2637062491, GIT_COMMIT_SHA=e8e2359b407acbef5982e190e38c9a9af51fa2b2, GIT_BRANCH=main
Python version: 3.9.2 64bit (/usr/bin/python3)

Installed plugins:
vdk-control-service-properties (from package vdk-plugin-control-cli, version 0.1.527956211)
vdk-execution-skip (from package vdk-plugin-control-cli, version 0.1.527956211)
vdk-plugin-control-cli (from package vdk-plugin-control-cli, version 0.1.527956211)
vdk-ingest-file (from package vdk-ingest-file, version 0.1.461192871)
vdk-sqlite (from package vdk-sqlite, version 0.1.477708478)
vdk-server (from package vdk-server, version 0.1.487944116)
vdk-ingest-http (from package vdk-ingest-http, version 0.2.477708478)
```

**Comment by murphp15** [comment]
@zverulacis  can you tell me which version of kubernetes you are on? 
Run the command `kubectl version` to get this information?

**Comment by ivakoleva** [comment]
@zverulacis please check https://github.com/vmware/versatile-data-kit/pull/1190, after merge you can install the plugin and use it to work with properties stored on your local FS (see README.md).
A simple workaround - of installed and running Control Service prerequisite -> just to store locally a secret for dev/demo purposes using Properties API.

**Comment by murphp15** [comment]
@zverulacis  
I was able to reproduce this error by manually configuring a newer version of Kubernetes for the kind cluster.
Looking at the Kubernetes deprecation guide online it describes the error you are seeing as something that would exist when using v1.25+.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
The version of Kubernetes is explicitly set in the code for the kind cluster.
Did you do something strange when creating the cluster?

**Comment by murphp15** [comment]
The issue can't be released on the latest version of vdk.
