### ISSUE TITLE
Add requirements to "vdk impala-query --help" and improve output

### ISSUE THREAD

**Issue by dvalkova** [vmware/versatile-data-kit#1199]
**What is the feature request? What problem does it solve?**
There are additional configurations that a user needs to make before running "vdk impala-query" (set username, password and authorization mechanism as environment variables). These are not present in the "vdk impala-query --help" prompt, however. 
Also, the output of the command does not contain column names and is hard to read since the columns are not aligned properly (see screenshot).

![image](https://user-images.githubusercontent.com/17336831/193023788-2273f7d0-8088-4dc5-a168-961320f09304.png)

If possible, it would be also nice if the user doesn't need to hard-code their password and store it in an environment variable.

**Suggested solution**
Add the prerequisites to "vdk impala-query --help".
Add column names and align columns in the output of the command.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale. 

A possible better solution is to have one single 'vdk query' command instead.
