### ISSUE TITLE
VDK return non-zero return code on failure

### ISSUE THREAD

**Issue by djdillon** [vmware/versatile-data-kit#1207]
**What is the feature request? What problem does it solve?**
When doing `vdk run` locally, it would be nice to return a non-zero return code when the job fails. This would allow scripting during development that could support things like requested in https://github.com/vmware/versatile-data-kit/issues/1205

**Suggested solution**
Non-zero return code from `vdk` when run command isn't successful.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
