### ISSUE TITLE
Have nightly builds for vdk plugins, integration tests etc.

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#1254]
**What is the feature request? What problem does it solve?**
Nightly builds of the vdk plugins and integration tests would help ensure the stability of the project.

**Suggested solution**
We should have nightly builds of the vdk plugins and integration tests.

**Comment by tozka** [comment]
I think we can schedule a [Gitlab Scheduled Pipeline](https://docs.gitlab.com/ee/ci/pipelines/schedules.html). 
We can mark certain Gitlab Jobs using https://docs.gitlab.com/ee/ci/jobs/job_control.html#run-jobs-for-scheduled-pipelines

I do not think that we should make nightly releases. It would make it harder for us to determine what is new in last month (e.g what was released) and it's a bit misleading that there are changes to a component when there are not.
