### ISSUE TITLE
Pipeline control service should support job builder images from private docker repo

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#1264]
**What is the feature request? What problem does it solve?**
Customers might want to have the job builder image in a private repo instead of using the public docker repo which has throttling.

**Suggested solution**
To support a private repo like this we need to make changes to the job builder definition. 
The job builder configuration needs an additional field which will be the secret name to use for pulling the private image.  
It will be up to customers to set this secret in their clusters.

**Comment by sabadzhiev** [comment]
Triaged. Closed as being already resolved.
