### ISSUE TITLE
Implement Object Oriented Design of invoking meta jobs

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#1271]
Currently meta jobs are specifed as dictionary of some fields. 

There's is a design to have API Meta Job and and IMetaJobInput so that users instead of calling

run_meta_job(custom_dict) , then can call run_meta_job (new MetaJob())

The approach with custom dict is easier for non software developers to use though as it's really configuration - no need to create pesky classes and related them to each other. 

But for maintenance purposes (of the code) and if we want to express more complex cases we should be OOP model as well. 

_Originally posted by @tozka in https://github.com/vmware/versatile-data-kit/pull/1249#discussion_r1005574353_

See also https://github.com/vmware/versatile-data-kit/pull/1640#discussion_r1108634403

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
