### ISSUE TITLE
Extract Remote Data Job control logic in shared library

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#1280]
Extract a lot of configuration and related code for interacting with vdk-control-service that is used both by vdk-meta-jobs and airflow provider and likely vdk-control-cli 

See following comment for example:    

     that class should either implement/extend a core concept, or become a part of it itself...
this plugin seems to describe the domain model for the first time, that should be available to reuse in general - and to keep consistent; 
maybe have this as an additional effort

_Originally posted by @ivakoleva in https://github.com/vmware/versatile-data-kit/pull/1249#discussion_r1009570651_

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
