### ISSUE TITLE
VDK JupyterLab Front-end Extension

### ISSUE THREAD

**Issue by duyguHsnHsn** [vmware/versatile-data-kit#1282]
**What is the feature request? What problem does it solve?**
For the VDK Jupyter integration we need to add elements to the Jupyter UI such as buttons, menus, etc. Thee elements should replace VDK CLI commands. The user should be able to do as many VDK operations as possible with the UI.

**Suggested solution**
 We should create a JupyterLab front-end extension which should add an VDK menu which will consist of VDK commands (see [jlab-extension-docs](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html) for more information).

**Comment by sabadzhiev** [comment]
Triaged. Closed. 

Will be handled with the work for Jupyter Integration MVP.
