### ISSUE TITLE
Add support for simple unit tests for helm chart(of the control service)

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#1286]
**What is the feature request? What problem does it solve?** 
At the moment we test a helm chart by deploying it.  
This catches a lot of bugs but it won't catch bugs relating to our charts not working on newer/older versions of k8s compared to the one we are deploying on.
It also doesn't catch issues that are only exist for certain configs as we only use a single config when deploying to the CICD cluster.
Suggested solution  
Use helm unit tests https://helm.sh/docs/topics/chart_tests to write a basic unit test which ppl could use as a template moving forward.  
The goal of this ticket would not be to have good coverage but simply to get a first test created.
Desired outcome would be that moving forward we can test:  
test different configs for helm  
test different versions of the generated kubectl yaml file

**Comment by tozka** [comment]
I think helm test is slightly different. It's after the installation test. After you install helm chart, you run a simple job. We have vdk-heartbeat which does the same thing. 

I think we need tests that can run before installation. It would be best to run at the same time as the unit tests  - before being merged. 

I think we are looking something more inline with this https://learnk8s.io/validating-kubernetes-yaml
