### ISSUE TITLE
Java-based components dependency versions auto-advancing

### ISSUE THREAD

**Issue by ivakoleva** [vmware/versatile-data-kit#1308]
**What is the feature request? What problem does it solve?**
Java-based components dependency versions auto-advancing that is compliant to our current python components release, and also effortless to continuously support. The current Dependabot approach performs constant background automated monitoring for release, that needs to be manually supervised for merging in addition by someone explicitly dedicated. It generates one noisy contributors experience towards new PRs activity notifications also. 

**Suggested solution**
We may consider the python components compliant approach, like for example
https://www.mojohaus.org/versions-maven-plugin/examples/advancing-dependency-versions.html
And there is the Gradle way:
https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies

The result is, the release cadence will match the functional changes made, and the PR author will happen to merge transparently with their change, or create a ticket and pin to last version in case needed. Oppositely to a 

**Additional context**

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
