### ISSUE TITLE
Jupyterlab - directory browsing

### ISSUE THREAD

**Issue by duyguHsnHsn** [vmware/versatile-data-kit#1341]
**What is the feature request? What problem does it solve?**
Add a directory browser. So when using VDK Jupyter, instead of copy pasting the directory path to an input element, the user can browse through the directories and chose the directory like that.

**Additional context**
Since it might bring some security problems further research should be done. 
If it is feasible  it can be implemented as an enhancement since it will make using the UI easier.

**Comment by sabadzhiev** [comment]
Triaged. Closed. 

All the usability issues related to Jupyter lab extension will be handled as part of the MVP Alpha work.
