### ISSUE TITLE
Stop using deprecated module imp, pgk_resources

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#1353]
**What is the feature request? What problem does it solve?**
In https://github.com/vmware/versatile-data-kit/blob/7f6e273319ce8255606de0f7d98c3e2b38889ae5/projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py#L82 we are using imp module to load source code. 

But the[ imp module is deprecated](https://docs.python.org/3/library/imp.html) in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses 

All warnings from vdk: 

```
../../../../../../usr/local/lib/python3.11/site-packages/vdk/internal/cli_entry.py:11
  /usr/local/lib/python3.11/site-packages/vdk/internal/cli_entry.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import iter_entry_points
../../../../../../usr/local/lib/python3.11/site-packages/vdk/internal/builtin_plugins/run/file_based_step.py:3
  /usr/local/lib/python3.11/site-packages/vdk/internal/builtin_plugins/run/file_based_step.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
    import imp
tests/test_vdk_trino_lineage.py:22
  /builds/vmware-analytics/versatile-data-kit/projects/vdk-plugins/vdk-trino/tests/test_vdk_trino_lineage.py:22: PytestCollectionWarning: cannot collect test class 'TestConfigPlugin' because it has a __init__ constructor (from: tests/test_vdk_trino_lineage.py)
    class TestConfigPlugin:
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

```

**Suggested solution**
Use importlib as suggested ?

**Acceptance Criteria**
* deprecated module is replaced 
* vdk run works in Python 3.12 alongside those form 3.7 to 3.11
* The functionality of loading Python modules from source files at runtime should remain intact

**Comment by sabadzhiev** [comment]
Triaged. We will keep it, as we need to fix it before the release of Python 3.12(oct 2023).
