### ISSUE TITLE
Support for Python 3.11 (vdk-snowflake)

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#1397]
**What is the feature request? What problem does it solve?**

Python 3.11 is officially released now and latest versions of Operating systems are starting to default to it. 
We should make sure we support it in our python applications

**Suggested solution**
Add tests for python 3.11 for all distributions that test against multiple versions . 
This will happen in multiple PRs and this issue will be closed after all PRs are merged succesfully

**Comment by ivakoleva** [comment]
Should the PR https://github.com/vmware/versatile-data-kit/pull/1395 cover the entire work on this ticket? Because it seems by merging it, the issue will be closed.

**Comment by tozka** [comment]
> Should the PR #1395 cover the entire work on this ticket? Because it seems by merging it, the issue will be closed.

Clarified the description.

**Comment by tozka** [comment]
Consdier updating job-builder as well see https://github.com/vmware/versatile-data-kit/pull/1395#issuecomment-1337241828

**Comment by ivakoleva** [comment]
> Consdier updating job-builder as well see [#1395 (comment)](https://github.com/vmware/versatile-data-kit/pull/1395#issuecomment-1337241828)

I don't quite understand this separation made. If we change the default vdk-core python version, should we change the language level used in the builder  accordingly? If yes, then this should apply to the upper python version supported as well.

**Comment by ivakoleva** [comment]
> What do you mean by changing the default vdk-core python version ? Default where ? In Control Serviec tests ?

That is a funny question, the default Python version should match in all VDK components :) There shouldn't be discrepancies in python versions across components, to minimise risk of discrepancies, unless there is a reason for them to explicitly differ.

> This issue is only about adding official support for 3.11 . And it's done by adding tests everywhere where we already test against multiple versions and changing python_requires where needed.

The issue states (generic) support  for 3.11, or at least not mentioning nor labelling any component in particular. I want to prevent the issue closing with only covering vdk-core and calling it done

**Comment by tozka** [comment]
The only one left is vdk-snowflake. The underlying connector library did not support 3.11 . 
Support seems to have been added a few hours ago now though - https://github.com/snowflakedb/snowflake-connector-python/pull/1349 

So we might be able to ugprade.
