### ISSUE TITLE
Data Job Debugging Plugin

### ISSUE THREAD

**Issue by doks5** [vmware/versatile-data-kit#1416]
**What is the feature request? What problem does it solve?**
Deployed data jobs can fail for multiple reasons. Usually, the solution for troubleshooting the errors is to investigate execution logs or reproduce the error locally.

This works in most cases, but does not work when the component that fails does not produce logs, if logs are missing altogether or if a dependency (either of vdk or the data job itself) fails for some reason.

To solve such issues, it would be nice to have troubleshooting tools as part of vdk, which can do a thread dump for example and send it to an endpoint, or log some specific information about the execution.

**Suggested solution**
One solution could be to have a plugin that can be part of vdk package bundle, and which has debugging/troubleshooting tools that can be configured in case a deployed data job needs to be debugged remotely.

**Additional context**

**Comment by doks5** [comment]
Related Pull Request: https://github.com/vmware/versatile-data-kit/pull/1423

**Comment by sabadzhiev** [comment]
Triaged. Closed as being already resolved.
