### ISSUE TITLE
Upgrade to java 17 or greater

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#1440]
**What is the feature request? What problem does it solve?**
Upgrade to java 17 or greater. 
The newest release of spring requires feature in java 17. 
And in its upgrade guide it lists being on java 17 as a prerequisite https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0. 

At the moment there are 3 PRs failing because they need the java 17 upgrade 
https://github.com/vmware/versatile-data-kit/pull/1436 
https://github.com/vmware/versatile-data-kit/pull/1434
https://github.com/vmware/versatile-data-kit/pull/1433

**Suggested solution**
I have started the update here https://github.com/vmware/versatile-data-kit/pull/1439.

**Comment by murphp15** [comment]
This ticket is currently blocked by https://github.com/vmware/versatile-data-kit/issues/1526

**Comment by tozka** [comment]
We should upgrade to Java 17 as it is the last LTS release (https://adoptopenjdk.net/support.html)
