### ISSUE TITLE
vdk-database plugin

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#1444]
**What is the feature request? What problem does it solve?**

Currently we have different database plugins - for implaa, greenplum, snowflake, sqlite, trino, etc. 

Each database plugin has some different level of maturity but each overall share the same functionalities (be it aspiration , not yet implemented) :

* Level 1 (a) - Managed Query - wrap the raw connection to provide manage DB API (PEP249) to users 
* Level 1 (b) - Configurability - provide configuration options that can be set by plugin, Control service or env variables 
* Level 1 (c) - CLI command - provide vdk xxx-query command to execute queries against that db 

* Level 2 - Ingestion - Ingest data into the database automatically when using job_input.send_xxx_for_ingesiton.

* Level 3 - Modeling Templates - templates to create fact and dimension tables into that database 

* Level 4 (a) - Error recovery - handle error cases automatically and try to recover from them 
* Level 4 (b) - Error classification - distinguish between user (e.g syntax error, timeout) and platform (server downtime) errors 

* Level X - Lineage - provided out of the box for each from vdk-lienage or custom lineage built-in in the plugin 

Level 1 is the first thing we provide when we create new plugin. 

and if you look at the code for each level it's very much the same. 
For Level 1 - the only difference is basically the "connect" functional and possibly some configuration parameters 
For Level 2 - the "insert query" might be different but otherwise everything is the same 
For Level 3 - again the SQL syntax for how to select, insert, filter some things is different but largely the "algorithm" for how the template works is the same 
For Level 4 (a) - As we have only one impl - for impala. It's hard to say. But it's likely  different across each plugin as it largely depends on the implementation of the DB - each db fails in different ways and has different corner cases. 
For Level 4 (b) - There are some common parts. Most db do follow the standard - https://peps.python.org/pep-0249/#exceptions - and report errors - so generally [OperationalError](https://peps.python.org/pep-0249/#operationalerror) would be a Platform error while [ProgrammingError](https://peps.python.org/pep-0249/#programmingerror) would be a User Error. 

The point I am making is there are a lot of overlap between db plugins. And creating a new plugin you basically copy paste another plugin code and edit to follow the syntax of the Database. I think we have enough different plugins that we can extract a lot of common logic in vdk-database base plugin and only things like SQL syntax or some db specific configuration is provided in the db specific plugin

**Suggested solution**
Create vdk-database plugin which will contain most of the boilerplate and common logic and provide interfaces for db specific plugin to implement . 

E.g we'd need an interface to connect to database  (think [template method pattern](https://refactoring.guru/design-patterns/template-method) ) 
```
def create_connection_inteface(conf: Configuration) 
   return Initailzied raw PEP 249 compatible connection , which will be wrapped in Managed Connection
```
Whikle the base plugin will create the ManagedCOnnection, would create the CLI query command, would create default error classification ,etc. 

SImilarly for others. 

More details in VEP

**Additional context**

**Comment by sabadzhiev** [comment]
Triaged. We will keep it, as being an Idea.

**Comment by tozka** [comment]
Related bugs to be considered #512

**Comment by antoniivanov** [comment]
Duplicate of https://github.com/vmware/versatile-data-kit/issues/2421
