### ISSUE TITLE
Migrate VMware's internal ui screens into the open source project

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#1507]
**What is the feature request? What problem does it solve?**
At the moment the VDK needs to be interacted with through either the VDK CLI or web requests. 
Neither of which are beginner/user friendly.
VMware has already built screens for VDK but at the moment they live in private repos in VMware. 
Most likely this will greatly help with the adoption of VDK and will improve user experience massively. 

**Suggested solution**
This needs to be handled by VMware employees. The details of this will be spared from the open source project.

**Comment by sabadzhiev** [comment]
Triaged. 

Closed as being already resolved with the VDK Operation UI Opensourcing initiative.
