### ISSUE TITLE
Upgrade to newer kerberos libraries 

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#1526]
**What is the feature request? What problem does it solve?**
At the moment we use extremely old libraries for kerberous auth. 
https://mvnrepository.com/artifact/org.springframework.security.kerberos/spring-security-kerberos-web/1.0.1.RELEASE

It hasn't been update in 8 years. 
It depends on classes in the JDK that aren't easily accessible in JDK 17 onwards.

People online say that we should migrate to apache kirby: https://stackoverflow.com/a/69479644/6401281

**Suggested solution**
Migrate to apache Kirby or a similar framework (https://github.com/bedrin/kerb4j)

**Comment by tozka** [comment]
It does seem we have 2 optoins 
A) Either adopt the latest version of spring security kerberos web by compiling and releasing it ourselves. 
B) Adopt https://github.com/bedrin/kerb4j . It does have spring integration and although there are not updates in last year . It's still more recently updated than the spring web and also the maintainer has stated that there are not major issues. 

So I'd recommend going with kerb4j. I haven't tried it out yet to see how seamless and easy the integration is (hopefully just renaming a few packages and upgrade gradle manifest). But at worst case we. should be able to do it in 2 or 3 days even if we hit some issues.

**Comment by sabadzhiev** [comment]
Triaged. Closed as being already resolved.
