### ISSUE TITLE
Support RUNNING status in Jobs Query (the GraphQL) endpoint

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#1542]
**What is the feature request? What problem does it solve?**

Look at [VDK Control Service JobsQuery endpoint (/data-jobs/for-team/x/jobs)](https://iaclqhm5xk.execute-api.us-west-1.amazonaws.com/data-jobs/swagger-ui/index.html#/Data%20Jobs/jobsQuery) 

It supports returning list of jobs and details about them. Including LastExecutionStatus per Data Job. 

Currently this returns the last finished job execution status. And it does not show RUNNING data jobs. 
This is making it much harder for end users to understand what is going on with their jobs and to see if some jobs are currently running and how many , etc. Which makes it harder to operate and manage multiple jobs. 

As a workaround users can go and see each individual job and then they can see running status as [dataJobExecutionList endpoing](https://iaclqhm5xk.execute-api.us-west-1.amazonaws.com/data-jobs/swagger-ui/index.html#/Data%20Jobs%20Execution/dataJobExecutionList). 

UI implemented on top of it rely on JobsQuery endpoint to efficiently present them with information about many jobs and we should add RUNNING status there as well. 
 

**Suggested solution**

Add support for LastExecutionStatus to return RUNNING status as well if job is running at the time of API invocation. 

The JobsQuery (GraphQL) endpoint fetches all execution data from the database ([see here](https://github.com/vmware/versatile-data-kit/blob/dc23c640a87e561cb9e7b31d090c6de85d029229/projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/ExecutionDataFetcher.java#L160)) 

It's DataJobMonitor that updates LastExecution status, time and duration ([see here](https://github.com/vmware/versatile-data-kit/blob/3507c2dfdcfe5dba3187df639df246fad5820de9/projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMonitor.java#L208))

The change for detecting status is [here](https://github.com/vmware/versatile-data-kit/blob/152f7724a5c4c3d3e6cbfb11e016fbf657b7cd5b/projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java#L1519) 

There there is "runningJobExecutionsConsumer" which tracks running jobs but does not persist the info in the DB. 
It's an option to simply have the watcher in DataJobMonitor update the status of the execution also for Data Jobs. But we need to see how often is it called .. 
We want to update it only once to running (when it changes to the pod status changes to running).

Also the logic for determining teh status should be consistent the one in [JobExecutionResultManager](https://github.com/vmware/versatile-data-kit/blob/3e17387e9ceb087540382cc7a850e5361c05fa35/projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionResultManager.java#L92) 

**Additional context**

cc @mivanov1988 @murphp15

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale. 

Will be reopen once we put this in our roadmap.
