### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by zverulacis** [vmware/versatile-data-kit#1569]
**What is the feature request? What problem does it solve?**
- Documentation is not structured well to be intuitive
- documentation is scattered
- repetitive
- difficult to navigate
- difficult to find documentation easily 
- documentation and different (use) cases are found difficult
- Documentation repeats and points to itself
- Missing documentation 

**Suggested solution**
Restructuring of documentation, in the Wiki. A new way of structuring the wiki must be created, agreed upon, and implemented. 
No new documentation needs to be written as part of this issue. Only existing documentation refactoring is required. 
A separate ticket for implementation can be created if the estimation is inaccurate.

**Additional context**

**Comment by sabadzhiev** [comment]
Triaged. This is a doc effort, that we are currently working on.

**Comment by antoniivanov** [comment]
Closing this ticket as it's tracekd as milestone: https://github.com/vmware/versatile-data-kit/milestone/7
