### ISSUE TITLE
csv-ingest error

### ISSUE THREAD

**Issue by zverulacis** [vmware/versatile-data-kit#1572]
**Describe the bug**
During the interviews about problem definition, it was identified that csv-ingest is throwing errors on a fresh install. This needs to be tested and verified and fixed if the issue exists.

**Steps To Reproduce**
install fresh quickstart-vdk 
try out csv-ingest 

**Expected behavior**
possibly error
I am sorry I can't tell you more because I don't know what exactly the error was, but this needs to be checked. 

**Version  (please complete the following information):**
no info on this

**Additional context**
The person also explained that they didn't understand what was the expected outcome, it could be that the expected outcome needs to be documented. 

So as part of this ticket please make sure that the documentation about csv-ingest is explaining what it does and why it exists.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
