### ISSUE TITLE
Plugin Development Documentation 

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#1585]
**What is the feature request? What problem does it solve?**
Currently the best doc for how to develop a plugin is here: https://github.com/vmware/versatile-data-kit/tree/main/projects/vdk-plugins#write-your-own-plugin

But it doesn't really go into details on what type of plugins is possible to develop
It briefly shows the type of plugin hooks that are available - [here](https://github.com/vmware/versatile-data-kit/tree/main/projects/vdk-plugins#types-of-plugins)
But it needs to explain what you (as a plugin dev) can do with those types. 
What is the implication of having plugin in vdk_start phase vs job_initalize phase, etc. 

**Suggested solution**

* Extend the diagrams and make them more explanatory adding example use case for each hook
* Create gif/video that visualize the plugin flow
* Create examples for a few plugins (or refer to existing ones (https://medium.com/geekculture/data-engineering-tricks-how-to-get-dirty-data-cleaned-through-vdk-60eeeda11ba0)

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
