### ISSUE TITLE
vdk-meta-jobs: misleading error 

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#1591]
*{*}What is the feature request? What problem does it solve?{*}*

From a customer :

", our meta job is failing with the following error An exception occurred, exception message was: The job moonshine-prod-daily_overhang_risk has not been registered. Use register_job first. When we try to manually execute the job moonshine-prod-daily_overhang_risk there is no such problem. What does use register_job first mean? Could you please help?"

Later it was seen that it is "it was caused by a typo in a job name listed in the depends_on configuration of another job"

The error is misleading. User facing error should provide clear details so user can auto-recover themselves quickly - [https://github.com/vmware/versatile-data-kit/wiki/Coding-Standard#error-handling]

*{*}Suggested solution{*}*

Better error.

 

*Acceptance Criteria:* 
* The configuration list is properly validated before being built into a dag for : 
 * job name/team name exists in the Control Service 
 * dag structure (spelling mistakes for example)

**Comment by gageorgiev** [comment]
Addressed in https://github.com/vmware/versatile-data-kit/pull/1592
