### ISSUE TITLE
Control Service: CI/CD optimization

### ISSUE THREAD

**Issue by mivanov1988** [vmware/versatile-data-kit#1593]
**Describe the bug**
The pipeline which runs after the merge on `main` branch is not very efficient. 

Here are the jobs and their durations:
![image](https://user-images.githubusercontent.com/40535952/216627807-76ee77aa-9b9e-4dcc-9726-101d8430505a.png)

1. `control_service_build_image` and `control_service_integration_test` jobs are not needed as they are executed in the preceding pipeline.
2. `control_service_publish_image` job runs tests before the image publication.

**Comment by tozka** [comment]
> control_service_build_image and control_service_integration_test jobs are not needed as they are executed in the preceding pipeline.

The preceding pipeline is the one run before the PR is merged, is that correct? 

We use rebase strategy for merging and require the pipeline to run with the latest changes from main. This means that the top of the feature branch when merged should be the same as main. Assuming this is true, the pipeline jobs run on merge should be redundant and we can remove it. 

control_service_publish_image -> technically we need not run test here as well .

**Comment by mivanov1988** [comment]
> 
> The preceding pipeline is the one run before the PR is merged, is that correct?
> 

That's correct.

**Comment by sabadzhiev** [comment]
Triaged. We have refactored the CI/CD for VDK significantly.
