### ISSUE TITLE
Control Service: Backwards compatibility for the K8s Cronjob API

### ISSUE THREAD

**Issue by doks5** [vmware/versatile-data-kit#1595]
**Describe the bug**
If there are deployed data jobs which use the v1beta1 API, and a switch is made to the V1 API, through setting the `datajobs.control.k8s.k8sSupportsV1CronJob` flag, these jobs are suddenly shown as NOT DEPLOYED, and cannot be properly managed.

**Steps To Reproduce**
1. Set up a k8s cluster.
2. Deploy some test data jobs.
3. Switch the `datajobs.control.k8s.k8sSupportsV1CronJob` flag and redeploy the Control Service.
4. Execute `vdk deploy --show` on any of the already deployed data jobs.

**Expected behavior**
The expectation is that data jobs can be properly managed irrespective of the cronjob API used.

**Additional context**
There is a PR for fixing the issue: https://github.com/vmware/versatile-data-kit/pull/1580

**Comment by murphp15** [comment]
Will be closed by https://github.com/vmware/versatile-data-kit/pull/1580
