### ISSUE TITLE
vdk-frontend: Decide on Oauth provider for testing

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#1610]
**What is the feature request? What problem does it solve?**
VDK-frontend was copied from an internal VMware project. 
Internally it was using a VMWare solution for oauth for production and testing.
This solution can't be used for testing in the open source repo. 
We need to investigate possible alternatives.

**Comment by tozka** [comment]
In Control Service REST API we use https://console-stg.cloud.vmware.com/ (CSP).

Being consistent would be a good idea and considering that the UI would likely work against the Control Service it might be necessary (or how it would authenticate?) 

An alternative is to use Google (e.g people can login using Gmail) but then we need to set authorization rules(*) and change the control service to use google. Definite con of this approach is we can enable some functionality of the UI for anyone with gmail account (which providedly are more people then those with csp).

(*) With CSP we allow anyone who has a CSP Staging account (which is few and generally trusted) so we have not special authorization.
