### ISSUE TITLE
Improve security issues scanning 

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#1614]
**What is the feature request? What problem does it solve?**

The purpose of the story is to enable our testing and scanning procedure catch any security issues. 
Particularly and issues that are related to using vulnerable dependencies or new CVS. 

**Suggested solution** 
Some kind of dynamic and static code analysis. We've enabled some from Codacy but may need to be tuned .

**Comment by sabadzhiev** [comment]
Triaged. Since opening the issue, we have done improvements in the area.
