### ISSUE TITLE
frontend: Remove l10 support from shared components

### ISSUE THREAD

**Issue by DeltaMichael** [vmware/versatile-data-kit#1641]
### Overview

We do not support l10n in the applications consuming `@vdk/shared`. The l10 functionality should be removed.

### DoD

1. Remove l10 component files from `@vdk/shared`.
2. Remove the SimpleTranslateService
3. Refactor existing components to not pass the translate service and work without it.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
