### ISSUE TITLE
Local VDK Control Service installation error

### ISSUE THREAD

**Issue by yonitoo** [vmware/versatile-data-kit#1657]
**Describe the bug**
I am trying to install the VDK Control Service locally, following the Installation page in the Wiki. However, when I set up the environment with the prerequisites and trying to run 'vdk server --install', I am facing the following issue: 
'Error: No such command 'server'.'

**Steps To Reproduce**
1. Go to the main repo page
2. Click on 'Wiki'
3. On the right navigation bar, in the 'User Documentation' section click 'Installation'
4. Go to 'Install Versatile Data Kit Control Service' > 'Install locally'
5. Install the prerequisites (helm, docker, kind >=0.11.1)
6. Run 'vdk server --install'

**Expected behavior**
The expected behavior is to have the Control Service installed on my local machine with configured local installation of VDK to use it.

**Screenshots**
-

**Version  (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Version 
```
Versatile Data Kit (VDK)
Version: 0.0.429183053
Build details: RELEASE_VERSION=0.0.429183053, BUILD_DATE=Tue Dec 14 11:57:00 UTC 2021, BUILD_MACHINE_INFO=Linux runner-t4krtqay-project-28359933-concurrent-0g64vr 5.4.129-62.227.amzn2.x86_64 #1 SMP Wed Jul 7 00:08:43 UTC 2021 x86_64 GNU/Linux, GITLAB_CI_JOB_ID=1882700545, GIT_COMMIT_SHA=157094ee6f6b5a90c7734bf0ad7bbdb9f55fca04, GIT_BRANCH=main
Python version: 3.9.6 64bit (/usr/local/bin/python3)

Installed plugins:
vdk-control-service-properties (from package vdk-plugin-control-cli, version 0.1.417315215)
vdk-execution-skip (from package vdk-plugin-control-cli, version 0.1.417315215)
vdk-plugin-control-cli (from package vdk-plugin-control-cli, version 0.1.417315215)
vdk-trino (from package vdk-trino, version 0.1.415648530)
tms-taurus-vdk (from package tms-taurus-vdk, version 0.3.3161536)
vdk-ingest-file (from package vdk-ingest-file, version 0.1.415625538)
tms-base-vdk (from package tms-base-vdk, version 0.3161536)
vdk-ingest-http (from package vdk-ingest-http, version 0.1.428971094)
vdk-csv (from package vdk-csv, version 0.1.415625538)
--------------------------------------------------------------------------------
```
**Additional context**
Here is the output after running the command in my terminal:
```
vdk server --install               
Usage: vdk [OPTIONS] COMMAND [ARGS]...
Try 'vdk --help' for help.

Error: No such command 'server'.
```

**Comment by yonitoo** [comment]
The server is able to be installed when the Docker is running. However, when trying to run the Meta Job example, there is a problem with the deployment of jobs.
```
Usage: vdk execute [OPTIONS]
Try 'vdk execute --help' for help.

Error: ¯\_(ツ)_/¯

what: The Data Job 'example-meta-job' is not deployed.
why: The Data Job must be deployed.
consequences: Operation cannot complete since it expects the data job to have a deployment.
countermeasures: Deploy the Data Job and try again.
```

**Comment by DeltaMichael** [comment]
Closing in favor of https://github.com/vmware/versatile-data-kit/issues/1773
