### ISSUE TITLE
Add staging table prefix as optional parameter to scd1 template

### ISSUE THREAD

**Issue by sbuldeev** [vmware/versatile-data-kit#1665]
What is the problem that needs to be solved?
Currently, if a user has same table names across different schemas there will be a need of separate staging schema for each DWH.

This feature request is to add staging table prefix as optional parameter to scd1 template. The change will allow users to have single staging schema for all their DWHs.

**Comment by tozka** [comment]
Can you please provide an example. 

E.g what is the case 

```
job_input.execute_template(target_schema="vmc_schema", target_table="esx") 
```
and another job
```
job_input.execute_template(target_schema="vsphere_schema", target_table="esx")
```

And both produce staging_schema.vdk_check_esx table which conflicts 

? 

Is that the problem .

**Comment by tozka** [comment]
Why not prefixing the staging table with the schema name? I think this is unique combination ? And would provide the needed uniqueness. 

In any case you need to be able that The maximum number of characters allowed in Impala for a table name in Impala is 128 characters (https://impala.apache.org/docs/build/html/topics/impala_identifiers.html) and the solution need to take care of this.

**Comment by sbuldeev** [comment]
Yes, the example you provided describes perfectly our case.

Do you mean providing the target schema as a prefix for the staging table? 
If I reuse your example that would mean "staging_schema.vmc_schema_esx".

This case seems fine to me, except a user hasn't provided a staging schema and the target schema is used instead.
This would mean a table like this will be created "vmc_schema.vmc_schema_esx" which could be a little bit confusing.
I'm thinking of sticking to the current "vdk_check_" prefix, but also adding the schema to the table name. Something like "vmc_schema.vdk_check_vmc_schema_esx".

What do you think?

**Comment by tozka** [comment]
Yes - that's what I meant - vmc_schema.vdk_check_vmc_schema_esx . I think all tables used by vdk check should be prefixed the same way (wiht vdk_check_) to make them easer to find, separate, reduce chance of conflicts in case of same table name

**Comment by tozka** [comment]
Yes, next question is. How long it can become. Identifies must not be longer than 128 in Impala. Puting vdk_check_(which his 10 symbols + schema name which can arbitrary long . You should check inside your tables and use-cases which is the longer and likely you may find some that table + schema + prefix > 128) 

I was think that if it's longer than 128 ... what can we do 
A) We can hash it .eg. table name = vdk_check_ + hash("{target_schema}_{target_table} ") - that would work but make the table hard to decifer 
B) Or we can truncate it "vdk_check_{target_schema}_{target_t" (thought there's risk of conflict (schema.sales with schema.sales_currency table :) ) 
C) hash only the schema name . That might also work.

**Comment by sbuldeev** [comment]
Currently, the longest length based on our production data would be 66 symbols with prefix+schema+table. The table is called vcf_dw.map_of_release_bom_components_and_bundle_elements.
I assume that we won't hit a problem with our tables for now. 

My thoughts on the suggested approaches:
A) Seems the only suggestion that we could take for avoiding to hit the 128 limit and unique name conflicts at the same time. It would bring some more complexity in extracting the table name as well as additional complexity in implementation.
B) Truncating the names over 128 to fit the limit looks like measured risk as I don't think we will face many such cases. Moreover, if the tables are with same names after truncating this won't be a problem since the current logic covers recreating the table if any difference is found. I assume that the only risk here for really edge case scenarios is to increase a little bit the DDL statements that will be executed while processing.
C) If we are hashing anything I would prefer hashing schema + table as this way we are still not insured that won't hit the limit if the table name is lets say 120 chars. Moreover, there should be an additional action to find out what is the exact table checks are being ran on in case of duplicate name tables across different schemas.
D) If people are following the best practices for sticking to shorter self-explanatory names the limit will be hardly reached. However I don't think it is right to restrict them to have short schema/table names in order to be able to use this functionality.

If I had to choose one of these it would be B.

**Comment by imitevm** [comment]
I'd prefer sticking to raising an error. Schema+table name of 120 characters is unwisely long.
