### ISSUE TITLE
Upgrade kubernetes-client to latest

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#1714]
**What is the feature request? What problem does it solve?**
Currently, we use 16.0.2 version of kubernetes-client in control service project. 

We cannot currently upgrade because we still need to support APIs from 1.20 and we still need V1beta1CronJob (which is removed in latest version. 

And the following 3 need to be upgraded in one change: 
* io.kubernetes:client-java
*  io.kubernetes:client-java-api-fluent
* org.yaml:snakeyaml (can be upgraded after above 2)

See PRs open by dependabot: 

* https://github.com/vmware/versatile-data-kit/pull/1712
* https://github.com/vmware/versatile-data-kit/pull/1710
* https://github.com/vmware/versatile-data-kit/pull/1700

**Suggested solution**

Create PR that upgrades to latest version after we remove support for V1beta1CronJob

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale. 

This work depends on the Internal VMWare deployment, to upgrade to a Kubernetes version, that supports the requirements here.
