### ISSUE TITLE
Rework the meta jobs plugin not to use global variables

### ISSUE THREAD

**Issue by gageorgiev** [vmware/versatile-data-kit#1737]
**What is the feature request? What problem does it solve?**
Currently, the meta jobs module uses two global variables for its functioning, one for the team name, another for the config object. Using global variables is an antipattern.

**Suggested solution**
The global variables should be dropped and we should have a better way of getting the two values.

**Additional context**
Location of TODO: https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-plugins/vdk-meta-jobs/src/vdk/plugin/meta_jobs/plugin_entry.py#L19
Location of global vars: https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-plugins/vdk-meta-jobs/src/vdk/plugin/meta_jobs/meta_job_runner.py#L12

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
