### ISSUE TITLE
frontend: Configure minified CSS for exclusion from auto formatting

### ISSUE THREAD

**Issue by ivakoleva** [vmware/versatile-data-kit#1745]
**Describe the bug**
The minified *.min.(s)css files should not contain spaces. Those are now automatically added when evaluating formatting pre-commit hooks.

**Steps To Reproduce**
See https://github.com/vmware/versatile-data-kit/blob/main/projects/frontend/data-pipelines/gui/projects/ui/src/assets/css/clr-ui.min.css

**Expected behavior**
By design purpose, the minified CSS shouldn't be formatted to be human-readable, instead optimised for download performance.

**Screenshots**
n/a

**Version  (please complete the following information):**
n/a

**Additional context**
See pre-commit CSS formatting hook config https://github.com/vmware/versatile-data-kit/blob/main/.pre-commit-config.yaml#L145

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
