### ISSUE TITLE
frontend: Add gifs to VEP-1507 demonstrating each user journey 

### ISSUE THREAD

**Issue by DeltaMichael** [vmware/versatile-data-kit#1755]
### Overview

Currently, there are several user journeys described in VEP-1507. It would be beneficial to visualise the user journeys.

### DoD
1. Gifs for each user journey created and added to VEP-1507

### Blockers

https://github.com/vmware/versatile-data-kit/pull/1750

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
