### ISSUE TITLE
Control plane integration tests need to be run against many differnt k8s versions

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#1778]
**What is the feature request? What problem does it solve?**
We have recently seen a regression in VDK on an older version of k8s that wasn't caught by integration tests because integration tests only run on a newer version of k8s. 

We need to be able to run the integration tests on more than one k8s version.

**Suggested solution**
Either provision multiple k8s versions in the cloud or use kind to install versions locally during testing. 

**Additional context**
ticket addressing the regression: https://github.com/vmware/versatile-data-kit/pull/1777

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
