### ISSUE TITLE
Give ability for frontend to release alpha, beta, rc versions

### ISSUE THREAD

**Issue by gorankokin** [vmware/versatile-data-kit#1803]
**What is the feature request? What problem does it solve?**
Improve script that generate release version to take into account version.txt when there is alpha, beta, rc,...

**Suggested solution**
Support release of artifacts versions:
* `<major>.<minor>.<patch>-alpha.N`
* `<major>.<minor>.<patch>-beta.N`
* `<major>.<minor>.<patch>-rc.N`

**Comment by tozka** [comment]
What is the need for that? I know in general but for you and Super Collider? 

We use semantic versioning as we mark major, minor and patch version generally with same semantics as outlined in semver.org. 

With teh patch version being automatically generated on each release (based on Gitlab CI number) . 
We so have not needed to put the development status to the version itself. 

I understand it's commonly used in npm packages and I am not opposed to doing it but I want to understand better the need.

**Comment by sabadzhiev** [comment]
Triaged. The issue seems to be fixed.
