### ISSUE TITLE
Increase resources for frontend gitlab runners

### ISSUE THREAD

**Issue by gorankokin** [vmware/versatile-data-kit#1805]
**What is the feature request? What problem does it solve?**
CI/CD runners that serve frontend pipelines should have more resources, because runs are very slow and takes a lot of time to comes to an end

**Suggested solution**
Increase resources for frontend gitlab runners

**Comment by tozka** [comment]
@gorankokin How much more resources ?

**Comment by gorankokin** [comment]
What are the current one?
Today seems like runners works smoother than yesterday.

In Taurus CI/CD runners for UI build/test/release were with limits for CPU 2 and for Memory 4Gi or 6Gi and were working pretty much smooth.

**Comment by gorankokin** [comment]
I found in the repository that currently runners have 1CPU and 6Gi which is not bad.

**Comment by tozka** [comment]
I assume that current resources are enough. ANd I think the main root-cause was disk shortage which is resolved. I am closing this now.
