### ISSUE TITLE
vdk-jupyter: working with multiple notebooks

### ISSUE THREAD

**Issue by duyguHsnHsn** [vmware/versatile-data-kit#1822]
**What is the feature request? What problem does it solve?**

If you open a new kernel for each Jupyter notebook, the memory will not be shared between them. This can result in differences between the development of a notebook data job and its execution. Using vdk-notebook plugin, multiple notebooks can be included in the same job directory and executed in alphanumeric order. However, even if the notebooks are executed in order, in development phase working with the same instance of job_input or other variables between them is not possible due to the different kernels used. To share data between notebooks in this scenario, you can use alternative methods such as saving variables to files or using a shared database (which is not practical and good practice).

This can cause some problems in the scenario where we download a job and start working on it - the results of the job can be different than expected because of that difference in development phase and execution phase, or at least cause some confusions since every notebook will be a different running process.

We should fix the problem so there is no difference in the development and the execution of the data job.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale. 

We will reopen, once we identify the need for it.
