### ISSUE TITLE
Use package-lock.json for @versatiledatakit/shared

### ISSUE THREAD

**Issue by gorankokin** [vmware/versatile-data-kit#1830]
**What is the feature request? What problem does it solve?**
Use package-lock.json for `@versatiledatakit/shared` in CI/CD pipelines and local development
* In that way we will be sure with what npm packages versions, the library is build.
  * That would give more confident that nothing would broke in other libraries that are produced internally in VMware SC project, because `@versatiledatakit/shared` is foundation for all UIs in SC.
  * For `@versatiledatakit/data-pipelines` we could continue using latest patches and minors depending of dependency resolutions.
    * Any problem here won't break in general, but would broke only data-pipelines feature, which is OK in context of SC resilience

**Comment by ivakoleva** [comment]
Find the dependency management strategy https://github.com/vmware/versatile-data-kit/tree/main/specs/vep-1507-vdk-operations-ui#dependency-management
To understand what npm packages are used to build the library -> we publish the exact package-lock file, with the CI/CD. That way, we have the libraries upgraded, and tested to verified during CI. That's also described in the specification.

**Comment by ivakoleva** [comment]
On the contrary, we have plans to actually unpin the dependencies https://github.com/vmware/versatile-data-kit/issues/1708

**Comment by sabadzhiev** [comment]
Triaged. Closed as being already resolved with #1708.
