### ISSUE TITLE
Data Pipelines Control Service frequent Authorization errors

### ISSUE THREAD

**Issue by gorankokin** [vmware/versatile-data-kit#2081]
**Describe the bug**
Data Pipelines Control Service throws dozen times per day Authorization error with message below and it slow down UI development and CI/CD e2e tests.
CI/CD pipelines e2e tests are failing multiple times because of Authorization error which on the other hand slows down UI libraries release.
```json
{
  "what": "Authorization server encountered an error: Webhook server returned non successful status code: 504.",
  "why": "The external system may be experiencing intermittent issues or there might be permanent misconfiguration or outage.",
  "consequences": "The current API operation failed.",
  "countermeasures": "Try the operation again in a few minutes and open a ticket to the SRE team if the problem persists."
}
```
reference links for failing e2e tests due to Authorization error:
* https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4299546667
* https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4300570262
* https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4301516806
* https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4302285193

e2e tests have some resilience implemented such test repeat on failure, but even there is such mechanism, pipelines are failing multiple times

**Steps To Reproduce**
There is no defined pattern when it happens, it's random

**Expected behavior**
Data Pipelines Control Service should return expected payloads without failing with Authorization error

**Version  (please complete the following information):**
Currently deployed service in VDK k8s namespace

**Additional context**
Authorization server encountered an error is happening because instability of dummy Webhook implementation

**Comment by tozka** [comment]
Fixed
