### ISSUE TITLE
[Control Service] Come up with a safer approach to job image configuration in helm chart

### ISSUE THREAD

**Issue by doks5** [vmware/versatile-data-kit#2100]
**What is the feature request? What problem does it solve?**
With the introduction of the [deploymentSupportedPythonVersions](https://github.com/vmware/versatile-data-kit/blob/main/projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml#L310) configuration, the fqdn of the image registry became part of the configuration map, instead of the previously used composite configuration approach.

This causes a situation, where the registry and its associated credentials need to be set in a separate configuration, thus leading to the possibility of unexpected errors, as mentioned in https://github.com/vmware/versatile-data-kit/pull/2075#discussion_r1197522079

We need to figure out a way to validate that the registries in the deploymentSupportedPythonVersions configuration are the same as the ones used for setting up the secrets.

**Suggested solution**
TBD

**Additional context**

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
