### ISSUE TITLE
publish images to github under a public image to avoid request throttling on docker hub

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#2102]
**What is the feature request? What problem does it solve?**
At the moment we have pipeline fail often because of docker hub request limits.
https://docs.docker.com/docker-hub/download-rate-limit/#:~:text=Docker%20Hub%20limits%20the%20number,pulls%20per%206%20hour%20period.

Github has no limits on the amount of images you can pull for public images. 

I have manually published some images to github to get the pipelines green.  
I have also created this PR to use github in integration tests which should result in us never getting throttled anymore https://github.com/vmware/versatile-data-kit/pull/2097/files.

**Suggested solution**
When we are publishing images to docker hub we should also publish them to github.

**Comment by sabadzhiev** [comment]
Triaged. Closed as being already resolved.
