### ISSUE TITLE
Investigate the use of Merge queue to optimize CICD resources

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#2128]
**What is the feature request? What problem does it solve?**
 As part of investigating CICD stability one of primary issues we've identified are redundant test runs due to extensive parallelism and the consequential resource starvation in the cluster. This inefficiency, furthermore, leaves behind a significant amount of unused resources, exacerbating the problem.

**Suggested solution**
One solution discussed was to enable the "cancel redundant pipelines" feature in GitLab. However, two problems persist with this solution: A) The feature is already activated, yet the issue continues; B) Even if fully functional, it may not be sufficient as pipelines, once initiated, might not cancel in time to prevent resource wastage.

A viable alternative could be the implementation of a [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue). This approach could optimize our resource usage and minimize redundancy.

Furthermore, considering VDK's predominately mono-repository structure, it would be prudent to maintain our current practice of not mandating rebasing during merges. In most cases, separate commits are not interrelated, indicating that a rebase might not always be essential or beneficial.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale. 

If issues with the CI/CD arise, we will reconsider this decision.
