### ISSUE TITLE
Generate a sitemap/mindmap proposal for the documentation and Wiki

### ISSUE THREAD

**Issue by zverulacis** [vmware/versatile-data-kit#2145]
**What is the feature request? What problem does it solve?**
In order to navigate and agree on the structure of our documentation, a mind-map/sitemap needs to be generated and agreed upon. 

**Suggested solution**
Create a mindmap image and agree with the rest of the team, get feedback from at least one user. 

**Additional context**
Here's the proposed solution 

**Structure proposal**

### User Documentation

1. Home
2. Installation
3. Getting Started
4. Examples
5. Dictionary

### [User Guide](https://github.com/vmware/versatile-data-kit/wiki/User-Guide)
..
add components documentation

### Community
Resources
Community meetings

### Dev Guide - link in the CONTRIBUTING.md
Coding Standard
PR best practices
CICD
Dependencies licensing

**Comment by antoniivanov** [comment]
Done in https://github.com/vmware/versatile-data-kit/issues/2488
