### ISSUE TITLE
Move Developer Documentation from the Wiki to the CONTRIBUTING.md

### ISSUE THREAD

**Issue by zverulacis** [vmware/versatile-data-kit#2146]
**What is the feature request? What problem does it solve?**
It was decided to move the Dev Docs from the Wiki to CONTRIBUTING.md

**Suggested solution**
Have links in the corresponding sections of CONTRIBUTING.md
Clean up the Dev Guide, remove the unnecessary pages

**Dev Guide - link in the CONTRIBUTING.md**
1. Coding Standard
2. PR best practices
3. CICD
4. Dependencies licensing

**Additional context**
Follow the source ticket if any questions: https://github.com/vmware/versatile-data-kit/issues/1720

**Comment by tozka** [comment]
Make sure to cover: 
 
 

- Remove Dev Guide page and move (the relevant) links to CONTRIBUTING.md
- Link the Doc Guide from the CONTRIBUTING.md
- CICD.md in the repo in https://github.com/vmware/versatile-data-kit/tree/main/support link in the CONTRIBUTING.md
- Link the best practices to CONTRIBUTING https://github.com/vmware/versatile-data-kit/wiki/How-to-prepare-a-new-PR

**Comment by zverulacis** [comment]
CONTRIBUTING.md:

Improve sequence: 
WHere to find all the docs - link to the wiki
Slack channel - to get in touch before you start contributing - we're all there
Check the issues and good first issues link
PR labels?
Improving docs
PR approval process
Guides on testing
list of steps
how to start dev environment - link

**Comment by zverulacis** [comment]
Markdown tips and tricks moved to Documentation Guide.
CONTRIBUTING.md section order changed 
Added local IDE and testing
