### ISSUE TITLE
Remove the repeating info from the Wiki

### ISSUE THREAD

**Issue by zverulacis** [vmware/versatile-data-kit#2150]
**What is the feature request? What problem does it solve?**

1. Installation instructions should be removed from the Getting Started - link Installation page
2. Remove Overview from the User Guide
3. Move Dev Guide and Documentation guide to the repo - in the CONTRIBUTING.md
4. Getting started shouldn't repeat the installation page and should reflect what's on it - remove the example
5. Remove Dev Guide from Wiki
6. Remove markdown tips and tricks from DevGuide
7. Delete Dev How to from Dev Guide
8. CICD.md in the repo in https://github.com/vmware/versatile-data-kit/tree/main/support link in the CONTRIBUTING.md
9. Link the best practices to CONTRIBUTING https://github.com/vmware/versatile-data-kit/wiki/How-to-prepare-a-new-PR
10. Basically, link all the relevant pages from the Dev Guide to the CONTRIBUTING.md
11. Documentation guide can be linked in the CONTRIBUTING.md and removed from the main Wiki page

**Suggested solution**
Follow the instructions above. 
Check with at least one user for feedback. 

**Additional context**
[Add any other context or screenshots about the feature request here.
](https://github.com/vmware/versatile-data-kit/issues/1720)

**Comment by tozka** [comment]
What's left: 
* Remove Dev Guide page and move (the relevant) links to CONTRIBUTING.md 
* Link the Doc Guide from the CONTRIBUTING.md 
* CICD.md in the repo in https://github.com/vmware/versatile-data-kit/tree/main/support link in the CONTRIBUTING.md
* Link the best practices to CONTRIBUTING https://github.com/vmware/versatile-data-kit/wiki/How-to-prepare-a-new-PR

**Comment by tozka** [comment]
Closing this one in favor of https://github.com/vmware/versatile-data-kit/issues/2146 where the remaining work is listed.
