### ISSUE TITLE
Capability to run the frontend and backend tests locally using quickstart-vdk

### ISSUE THREAD

**Issue by ivakoleva** [vmware/versatile-data-kit#2168]
**What is the feature request? What problem does it solve?**
We need to facilitate the community members and contributors, with providing a mechanism to use(run) the tests suite locally.

**Suggested solution**
Reuse the same entry point for running the tests locally, and wired in the CI/CD.

**Additional context**
Provide clear instructions on the tests suite usage.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
