### ISSUE TITLE
[SPIKE] 30 second video examples (multiple) for VDK capabilities

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#2214]
**What is the feature request? What problem does it solve?**
In order to be able to quickly and easily demonstrate what VDK can do , it would be beneficial to have short videos or even gifs that show it. 

**Suggested solution**

The "What VDK Can do" section is pretty good and the logos are great. 
We can further improve 
A) We should minimize the logs a bit to fit better on the screen
B) We can add links or even small videos or gif (if you click on the log) or maybe besides it that shows how this feature is used

**Comment by tozka** [comment]
The design can be seen here https://www.canva.com/design/DAFnq9ouriY/FxmviN90b9ofU5EvNV5HLQ/view?utm_content=DAFnq9ouriY&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by tozka** [comment]
Stories about publish are in separate milestone https://github.com/vmware/versatile-data-kit/milestone/11
