### ISSUE TITLE
VDK intro videos: 30s ingestion video

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#2404]
**What is the feature request? What problem does it solve?**

As part of https://github.com/vmware/versatile-data-kit/issues/2214 we need to create several 30s videos to introduce VDK

A video for the ingestion step needs to be created.
This video will show up in the Ingestion section of the README file.
This video also needs to be uploaded to YouTube and converted to GIF for the README file

For how to make a gif: https://github.com/vmware/versatile-data-kit/wiki/How-to-create-a-GIF

**Plan:**
1. Show the before and after (we have an image for that in the repo, but you can create your own example)
2. Zoom in on _after_ and show the VDK components - and highlight the code that automates the ingestion and explain it in text - in the video 

**Additional context**
Definition of done:
30s video is created
Uploaded to YT playlist
Uploaded to the repository

**Comment by zverulacis** [comment]
https://www.canva.com/design/DAFqgIoarmA/CRWXfLj7wlZqFGdtm2I2QA/edit?utm_content=DAFqgIoarmA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by zverulacis** [comment]
Updated link: https://www.canva.com/design/DAFq7Tc2vNk/3Qfi7ge5nOkEAbAEohEzgw/edit?utm_content=DAFq7Tc2vNk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by zverulacis** [comment]
Updates as per the feedback given
