### ISSUE TITLE
VDK intro videos: 30s plugins "Lego like extensibility" video

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#2405]
**What is the feature request? What problem does it solve?**
As part of https://github.com/vmware/versatile-data-kit/issues/2214 we need to create several 30s videos to introduce VDK.

A video for Plugins / other features needs to be created. 

This video will show up in the "What else you can do with VDK" section of the README file.
This video also needs to be uploaded to YouTube and converted to GIF for the README file
For how to make a gif: https://github.com/vmware/versatile-data-kit/wiki/How-to-create-a-GIF

**Plan:**

Example:
Show how user can find a list of plugins
Show how user can install a plugin 

Acceptance criteria: 
1. 30s video is created
2. Uploaded to YT playlist
3. Uploaded to the repository

**Comment by zverulacis** [comment]
https://www.canva.com/design/DAFqxvijibg/NLCP9_XAL3EjDdLereQ3Yg/edit?utm_content=DAFqxvijibg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
