### ISSUE TITLE
PrivateBuilderDockerRepoIT.testPrivateDockerBuildJob is unstable

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#2546]
**Describe the bug**
PrivateBuilderDockerRepoIT.testPrivateDockerBuildJob is failing intermittently  

For example https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4840729404

It's not yet clear why is it happening. Could be because of cluster load. Variable performance of some component. 

**Expected behavior**
Test passes every time. 
Or if test is not needed remove it. 
 
**Additional context**
For example : 
*  https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4840729404
 [testPrivateDockerBuildJob.failing.log](https://github.com/vmware/versatile-data-kit/files/12312872/testPrivateDockerBuildJob.failing.log)

**Comment by antoniivanov** [comment]
Another occurance : https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4876339150

**Comment by mivanov1988** [comment]
Another occurrence :https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4890907601

**Comment by mivanov1988** [comment]
Another occurrence: https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4965604188

**Comment by murphp15** [comment]
I am going to close this. 
It hasn't happened in a very long time. 

I looked through failed jobs and there are none in the past 6 weeks of this type. 

How I did this was search in https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs?statuses=FAILED for integration tests runs which failed on main.
