### ISSUE TITLE
[Spike]Compare different python progress bar libraries

### ISSUE THREAD

**Issue by DeltaMichael** [vmware/versatile-data-kit#2573]
## Overview

There are a number of options for displaying progress bars in python CLI applications.
We should research and find the best one for our use case.
A good place to start is comparing tqdm and progressbar(may be also others).

## Acceptance criteria
1. Do a PRO/CON analysis on different progress bar libraries and recommend the one we should use
2. Sync analysis with rest of team

**Comment by antoniivanov** [comment]
Completed in https://github.com/vmware/versatile-data-kit/pull/2647
