### ISSUE TITLE
Remove deprecated error reporting patterns from vdk plugins and vdk-core

### ISSUE THREAD

**Issue by DeltaMichael** [vmware/versatile-data-kit#2680]
### Overview

After https://github.com/vmware/versatile-data-kit/pull/2666, log_and_throw, log_and_rethrow and ErrorMessage were just kept for compatibility with vdk plugins that still use them. The ResolvableBy enums also have incorrect names under the current paradigm

### DoD
1. Replace log_and_throw and log_and_rethrow calls with report_and_throw and report_and_rethrow. Include separate logging where necessary
2. Remove the use of ErrorMessage and just pass the message lines
3. Remove the use of ErrorMessage to convert notifications to html and replace it with a private method
4. Rename ResolvableBy to ErrorType and ResolvableByActual to ResolvableBy
5. Split the error reporting, resolvable context and error classes into separate files (if this causes too much of a ripple in the code, open a separate ticket for it)

**Comment by duyguHsnHsn** [comment]
We will not be solving 4. here. It is described as new issue here: https://github.com/vmware/versatile-data-kit/issues/2768
