### ISSUE TITLE
vdk-structlog: cannot remove timestamp when using json format

### ISSUE THREAD

**Issue by DeltaMichael** [vmware/versatile-data-kit#2810]
## Steps to reproduce

1. Install vdk-structlog and configure as follows

```
logging_metadata=level,file_name,line_number,vdk_job_name
logging_format=json
```

2. Run an example data job

**Expected**

Timestamp not visible in log messages

**Actual**

Timestamp still visible in log messages

## Acceptance criteria
1. Fix the bug described above
2. Check this for other metadata fields
3. Create e2e tests that check for it if there aren't any

**Comment by gageorgiev** [comment]
this issue appears for a number of other fields, maybe we should expand the scope of it

**Comment by gageorgiev** [comment]
this issue appears for a number of other fields, maybe we should expand the scope of it
