### ISSUE TITLE
vdk-oracle: deprecate oracle-query in favor of sql-query

### ISSUE THREAD

**Issue by DeltaMichael** [vmware/versatile-data-kit#2940]
## Overview

All "-query" cli implementations have been deprecated in favour of the more generic sql-query. https://github.com/vmware/versatile-data-kit/pull/2649

It should be the same for Oracle. Note that this might break the test suite, because it uses oracle-query for validation.

## Acceptance criteria
1. oracle-query deprecated
2. sql-query used instead

**Comment by antoniivanov** [comment]
We need only remove the 'oracle-query' command and switch to `sql-query` in the test similarly done in [vdk-duckdb tests] (https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-plugins/vdk-duckdb/tests/test_plugin.py#L70)
