### ISSUE TITLE
Decide on if we should use confluence/jira or slack as the datasource

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#2990]
**What is the feature request? What problem does it solve?**
We want to build the type of RAG data population pipeline a big organisation would build. 
These both seem like good sources of data to me to use. 
Choose whichever one is easier to work with

**Definition of Done**
There should be a data job which runs and read from either confluence or jira.

**Comment by antoniivanov** [comment]
See example data job at https://github.com/vmware/versatile-data-kit/tree/main/examples/confluence-data-retrieval-example
