### ISSUE TITLE
[timebox] Create a postgres instance which is running internally so that we can save VMWare confluence pages in it 

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#3016]
**Overview**
Deploy a Postgres instance for demo in VMware using DSM (https://docs.vmware.com/en/VMware-Data-Services-Manager/index.html)

**Suggested solution**
Postgres instance with pgvector extension provisioned in DSM in VMware.

**Comment by stefan-pulov** [comment]
We have a DSM based Postgres instance with pgvector. Hence closing this one.
