### ISSUE TITLE
Use the insights on VDK SDK usage from Google BigQuery

### ISSUE THREAD

**Issue by yonitoo** [vmware/versatile-data-kit#3034]
**What is the feature request? What problem does it solve?**
The need for detailed and accurate statistics on VDK SDK usage, distinguishing real downloads from CI/CD ones. 
The idea is to query information on regular basis (daily/weekly/monthly) and recognise changes/tendencies among the users.

**Suggested solution**
3 possible solutions:

1. (not very simple but most convenient to maintain) Integration of BigQuery query results into[ the existing VDK Mode report](https://app.mode.com/vmware_inc/reports/179589458c9a) - a way to do this could be to create a SuperCollider Data Job that would ingest the information from BigQuery API into a table and then use it for the Mode report.
2. (more simple) Create a separate Mode report out of the BigQuery results - the BigQuery info might be directly used to create the Mode report.
3. (most simple if possible) Create a dashboard directly from the BigQuery results -> Chart tab.

The 3 different interval (daily/weekly/monthly) options has to be tested and the most suitable should be used - if we would attach it to our existing Mode report, the weekly option is recommended.

Useful queries: https://console.cloud.google.com/bigquery?sq=1036084278839:bab9ab393bc94036baf6b200a7dcef18

**Comment by DeltaMichael** [comment]
@yonitoo Please link the query in the dev guide and close the ticket.
