### ISSUE TITLE
[Spike] Evaluate Integration of LLamaIndex with VDK for RAG Application

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#3083]
[llamaindex](https://docs.llamaindex.ai/en/stable) is a library that helps build RAG applications. 

It provides some abstraction for details with datasets (including set of connectors), indexes,etc. See https://docs.llamaindex.ai/en/stable/getting_started/concepts.html 

[LLamaIndex](https://docs.llamaindex.ai/en/stable/) is designed to support RAG applications by indexing and retrieving relevant documents or data points. VDK offers capabilities in data processing and runtime, orchestration, state management, and metadata handling that could complement LLamaIndex's functionalities.

The goal is to evaluate how LLamaIndex and VDK can be integrated to improve RAG applications. This involves understanding the functionalities of both, and identifying complementary features. Good approach to do that is by re-implementing parts of an existing Confluence-based RAG demo pipeline to pinpoint integration points and gaps.

Suggestion tasks: 
- Gain a good understanding of LLamaIndex by deep divinginto the documentation
- Re-implementing parts of the Confluence-based RAG demo pipeline using LLamaIndex only. This can help identify specific areas where VDK can enhance the LLamaIndex-based pipeline. This could involve data orchestration, managing the state. Or vice versa where llama index can help building VDK functionality.  
- Build a document describing the evaluation process, findings, gap analysis, and recommendations for how integration could work  (What VDK provides, what llama index)

**Comment by duyguHsnHsn** [comment]
https://github.com/vmware/versatile-data-kit/wiki/VDK-and-LLamaIndex
