### ISSUE TITLE
Update copyright headers

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#3086]
As VDK is now owned by Broadcom and not VMware we should update the copyright headers to reflect that .

The change is “VMware, Inc.” can be replaced with “Broadcom”  (no inc) 

- First here https://github.com/vmware/versatile-data-kit/blob/main/NOTICE.txt 
- There was some automated way to update all files using I ma not sure if it would happen automatically upon change the above file . We use the following pre-commit hook:

 https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license

**Comment by DeltaMichael** [comment]
Check this guideline before changing anything https://docs.google.com/document/d/1Agp9QB7C_FiKDiyQwTpNXaYbYDRzujSREvF94yDCgMM/edit

**Comment by DeltaMichael** [comment]
There should be no bulk update, just change the header automation for new commits.
