### ISSUE TITLE
Wiki: team feedback

### ISSUE THREAD

**Issue by zverulacis** [vmware/versatile-data-kit#3095]
While the restructuring of the Wiki is in progress, some feedback on the structure is necessary to make it incremental: 

Please review and comment on the current state of wiki.

I'd need you to:
1. Give feedback about the Home page
2. General Structure of the Wiki
3. Each page in the structure
 - relevance (should it exist?)
 - content (does it make sense?)
 - location (is it in the right place?)
7. Any comments on improvements, what's missing?

This ticket is to gather and implement the suggestions. 

Acceprance criteria: 
- at least 2 people have reviewed and provided feedback. Changes as per the feedback are implemented.

**Comment by murphp15** [comment]
### Home page: 

I really like the home page. 
My only problem is with those anchor buttons. They have a very jumpy feel. But I still think it is better with them in than without it. 

### General Structure of the Wiki: 

**This is more a general comment about wikis in github.** 
Whenever I am working(contributing to/or just reading) with a github project I always clone it locally. 
If I'm looking for docs/how tos/etc.. I will always search the repo in intellij for the keyword etc I am looking for. 

When docs are in the wiki I don't find them. 

This has actually happened me on a number of occasions in our repo. Where I was looking for the docs on how to debug a job in intellij and couldn't find the docs. 


This is also a general complaint about github wikis. But its a bit weird that there is a pages section before the content layout part. but I much prefer the feel of looking for a page in the pages section.
Can we have a consistent layout between the two? Or even better get rid of the side bar and just use the pages part?  


I would change dictionary to glossary for the page title.




I will add more to this comment later

**Comment by zverulacis** [comment]
1. Overview is for both SDK and Control Service
2. The structure is good 
3. Getting started doesn't make sense anymore 
4. Data sources - spam and 100s of data sources and like .. .. .. check here. 
5. Python dependencies - part of the page about deployment 
6. In the CS Key concepts should be - Properties and Secrets - for the Key Concepts - take it from swagger-ui - https://supercollider.vmware.com/data-jobs/swagger-ui/index.html
6. UI installation is just together with control service and just access 
8. Plugins - each plugin has documentation - use each README
9. Root readme of plugins also is good - https://github.com/vmware/versatile-data-kit/tree/main/projects/vdk-plugins
10. Jupyter plugin in plugins 
11. config help and search by prefix
