### ISSUE TITLE
Deploy a RAG pipeline to a VDK cluster

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#3148]
**What is the feature request? What problem does it solve?**
A rag pipeline will be built as part of https://github.com/vmware/versatile-data-kit/issues/3147.

The goal of this ticket is to get that pipeline rewritten in a VDK data job. 
Only a single data job. 
use VDK for the postgres url etc...

**Comment by antoniivanov** [comment]
Which VDK cluster? We can use the SuperCollider . In the CICD there's no UI.

**Comment by murphp15** [comment]
@antoniivanov  it would be brilliant to have a UI. 
But will we be able to build big images on their cluster? 


is there anyway you can think of to get the UI working on the CICD cluster?

**Comment by antoniivanov** [comment]
It is fine to use SuperCollider for this. 

We can install teh sentence-transfomers dependency dynamically (and remove it from requirements.txt) 

https://github.com/vmware/versatile-data-kit/issues/3142#issuecomment-1956762676
