### ISSUE TITLE
[SPIKE] Create an example of writing to postgres using LLamaIndex

### ISSUE THREAD

**Issue by murphp15** [vmware/versatile-data-kit#3150]
**What is the feature request? What problem does it solve?**
For the demo we want to use postgres and llamaindex to write to it. 
This ticket is to become familiar with how to do this.

**Comment by antoniivanov** [comment]
@duyguHsnHsn  already did some research in this area. See her notes in https://github.com/vmware/versatile-data-kit/wiki/VDK-and-LLamaIndex

**Comment by gageorgiev** [comment]
https://docs.llamaindex.ai/en/stable/examples/vector_stores/postgres.html - according to this tutorial, llamaindex can be used to query from but not to ingest to a postgresql db

**Comment by gageorgiev** [comment]
https://medium.com/dataherald/how-to-connect-llm-to-sql-database-with-llamaindex-fae0e54de97c - another resource where a sqlalchemy db connection is required as a supplementary object; it seems like this is another opportunity to stress the benefit of having a VDK managed connection when building rag apps
