### ISSUE TITLE
vdk control service installation bug

### ISSUE THREAD

**Issue by ehsan-farzadnia** [vmware/versatile-data-kit#3173]
**Describe the bug**
The bug is detected when installing VDK control service on a host. 

**Steps To Reproduce**
1. Go to command line/ terminal in linux 
2. Run the following commands to ensure that all prerequisites (vdk SDK, kind, helm, and docker) have been installed properly. If any of them is not installed, install each one individually: 
   vdk version
   kind version
   docker version
   helm version

The output of the commands above are as follows:

![image](https://github.com/vmware/versatile-data-kit/assets/161824187/273f98d5-a9b6-48b9-995d-e9c87c7ef82d)
![image](https://github.com/vmware/versatile-data-kit/assets/161824187/469e023d-e58c-4e77-82ea-0512e356c60e)
![image](https://github.com/vmware/versatile-data-kit/assets/161824187/a22a4f8f-d672-462b-9caa-aa51a9377e66)
![image](https://github.com/vmware/versatile-data-kit/assets/161824187/40c283d1-bea7-4358-9302-897fb273cd39)

After successfully installing kind, helm, and docker on Ubuntu Jammy,

4. Then run vdk server --install
5. server log is attached!

**Expected behavior**
What we expected to happend after running 'vdk server -i' is to have VDK Control Service properly installed on the host. This is a prerequisite step for ingestion in the examples like incremental-ingest-from-db-example. 

**Screenshots**
![Screenshot 2024-03-01 135937](https://github.com/vmware/versatile-data-kit/assets/161824187/813543fd-5c64-442c-9d17-3350161172da)
![Screenshot 2024-03-01 140003](https://github.com/vmware/versatile-data-kit/assets/161824187/70b21310-2f82-49f9-85ff-e8ece034d1ee)

**Version:**
 - OS: Windows 11, and Ubuntu Jammy 22.04
 - Version: 0.3.1190994517 

**Additional context**
[server.log](https://github.com/vmware/versatile-data-kit/files/14459786/server.log)

**Comment by murphp15** [comment]
@ehsan-farzadnia  can you please check that the kubernetes cluster is in a healthy state?
IMO the simplest way to do this would be to download [lens](https://k8slens.dev/). 
Use it to check that you can connect to the k8s cluster and that some pods are running OK.

**Comment by ehsan-farzadnia** [comment]
@murphp15 I tried a lot but I couldn't create a kind cluster manually (error is attached)

![image](https://github.com/vmware/versatile-data-kit/assets/161824187/6e01cbeb-360a-4abd-b268-42c2aa11f768)


Also, my docker connection 

![image](https://github.com/vmware/versatile-data-kit/assets/161824187/8ac82896-2190-42f6-ab22-687c3ea51d16)

What is the problem?

**Comment by murphp15** [comment]
there error is saying you haven't created kind-cluster-config.yaml. 
Can you create that and try again.

**Comment by ehsan-farzadnia** [comment]
Hi Paul,

Please find attached my screenshot from the Linux terminal runnig the command. I did all the steps you proposed however a new error caused as I cannot fix it! Can you help me?

 
![image](https://github.com/vmware/versatile-data-kit/assets/161824187/ffb53155-e555-4585-96c5-0f4a342c87ba)


Thank you
Ehsan

**Comment by ehsan-farzadnia** [comment]
Hi @murphp15,

Please find attached my screenshot from the Linux terminal runnig the command. I did all the steps you proposed however a new error caused as I cannot fix it! Can you help me?

 
![image](https://github.com/vmware/versatile-data-kit/assets/161824187/de8e2f50-9057-49c5-988a-1bd6eff6012e)

Thank you
Ehsan

**Comment by murphp15** [comment]
can you try run that docker pull command outside of the install 
so 
```
docker pull kindest/node:v1.20.15
```

**Comment by ehsan-farzadnia** [comment]
Hi Paul,

I tried it out and manually attempted to pull that node but no outcome!

![image](https://github.com/vmware/versatile-data-kit/assets/161824187/9a24f127-b8b3-49ec-aec5-f1fda165352a)

E

**Comment by murphp15** [comment]
can you run the single failed command and see does it work?

**Comment by ehsan-farzadnia** [comment]
dokcer command is successfully pulled 

![image](https://github.com/vmware/versatile-data-kit/assets/161824187/5a02fead-fa08-4206-a29f-8edbb9af1b2f)


Then, after running "vdk server -i", again the same error message appears "faild to create cluster error message" ! 

![image](https://github.com/vmware/versatile-data-kit/assets/161824187/852e0b1c-a69b-40aa-a19d-83b3cf30902a)

![image](https://github.com/vmware/versatile-data-kit/assets/161824187/e787900d-caf6-4965-aaf9-67e86bc1e426)

says "kubelet is not running"

**Comment by ehsan-farzadnia** [comment]
I checked it out to see if kubelet it running or not with this command "systemctl status kubelet" 

![image](https://github.com/vmware/versatile-data-kit/assets/161824187/edfe298a-3fa7-46ad-88d0-b2e21aa7081e)

**Comment by murphp15** [comment]
We will look at this this sprint.

**Comment by murphp15** [comment]
@ehsan-farzadnia  we are actively looking into this and should have a solution this week.

**Comment by ehsan-farzadnia** [comment]
@murphp15 I get failure while installing kind Control Service in kind cluster ... as attached. Could you help me to fix it?

![error](https://github.com/vmware/versatile-data-kit/assets/161824187/f24bd92d-d3e3-4a44-aba1-9c2338a77e79)
