### ISSUE TITLE
vdk-core: replace hook in connection built-in plugin

### ISSUE THREAD

**Issue by DeltaMichael** [vmware/versatile-data-kit#3233]
https://github.com/vmware/versatile-data-kit/blob/82756aea42c260ab23f03cbfbda6769bbcf98ae8/projects/vdk-core/src/vdk/internal/builtin_plugins/connection/connection_plugin.py#L25

**Comment by duyguHsnHsn** [comment]
This should be part of: https://github.com/orgs/vmware/projects/35/views/1?sliceBy%5Bvalue%5D=Multiple+Databases+In+One+Job&pane=issue&itemId=56756213

**Comment by DeltaMichael** [comment]
Closing in favor of https://github.com/vmware/versatile-data-kit/issues/3164
