### ISSUE TITLE
Plugin Browsability UX improvements

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#363]
**What is the feature request? What problem does it solve?**
As a user I'd like to find out what plugins can I install? What do they do ? 
Currently those are listed in https://github.com/vmware/versatile-data-kit/tree/main/projects/vdk-core/plugins 

This is not a terrible solution. But we can be more user-friendly. 

**Suggested solution**
Something like https://docs.pytest.org/en/latest/reference/plugin_list.html might not be bad idea. 

But also we may create new plugin vdk-plugin-manager 
And it would introduce  `vdk plugin --list` command and/or `vdk plugin --search` to search and list plugins 
and `vdk plugin --name name-of-plugin --info` (which will print basically the readme of the plugin). That might be easier for users relying on CLI (where plugins usually are installed). 

Having UI with that info would be useful as well though.

**Comment by sabadzhiev** [comment]
Triaged. Closed as not relevant.
