### ISSUE TITLE
Define and document coding standards

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#386]
**What is the feature request? What problem does it solve?**
We need clearly defined coding standard for the project. There are some recommendation that are passed using worth of mouth but that is not very clear even to us existing contributors let alone new ones

**Suggested solution**
Create wiki with clear coding standards for java,python,helm charts 

 helm charts use same standard as bitnami https://github.com/bitnami/charts/tree/master/bitnami
Python is based on PEP 8
Java - ? Google style guide, We can reuse https://github.com/maltzj/google-style-precommit-hook
Error handling https://github.com/vmware/versatile-data-kit/blob/main/projects/control-service/CONTRIBUTING.md#error-handling
Logging

**Comment by ivakoleva** [comment]
Should we move error-handling section to a common CONTRIBUTING.md? At the moment, it's contextual to Pipelines Control Service, however it applies to all components

**Comment by tozka** [comment]
Also necessary to meet the following best practice as evaluated here - https://bestpractices.coreinfrastructure.org/en/projects/5363#analysis

 "The information on how to contribute SHOULD include the requirements for acceptable contributions (e.g., a reference to any required coding standard). (URL required) [contribution_requirements]"
