### ISSUE TITLE
Establish process for tagging major and minor releases

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#387]
**What is the feature request? What problem does it solve?**
Tagging releases is very standard practice - https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository and 
They can be easily seen in https://github.com/vmware/versatile-data-kit/releases/new
It would make it easier for users to navigate what artifacts are available.  And also easier to track change log/ release notes on what has changed so user can decide to upgrade or not.

**Suggested solution**
Not sure, We need some kind of process or automation: 
E.g user creat tag 2.1  (from 2.0) -> this automatically updates (automated commit) the version to 2.1 in the version.txt file (or where the version is) and create new entry in CHANGELOG updating the data 

Patch release are not tagged and are automated on each commit with successful CI pipeline

**Additional context**

**Comment by sabadzhiev** [comment]
Triaged. Closed as not relevant.
