### ISSUE TITLE
[TimeBoxed]Support Python 3.10

### ISSUE THREAD

**Issue by mnozhchev** [vmware/versatile-data-kit#390]
**What is the feature request? What problem does it solve?**
pip install quickstart-vdk fails on Python 3.10 with a very uninformative message. Also README.md says that vdk requires "Python 3.7+" which implies that Python 3.10 is supported.

**Suggested solution**
Test vdk on Python 3.10 and, then, update the setup.cfg metadata to include 3.10.

**Additional context**
![image (1)](https://user-images.githubusercontent.com/6613495/137323191-541ea2fe-1e0f-47ef-ab65-fd8735d8386f.png)

**Comment by tozka** [comment]
There are 3 components that need to be changed. We may split it into 3 bugs 

vdk-core: 

Test vdk on Python 3.10: 
Add [Gitlab CI Job](https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-core/.gitlab-ci.yml) (similar to the other ones for 3.7-3.9) vdk-core-simple_func_test_with_py310 and vdk-core-build_with_py310 (to vdk-core file -https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-core/.gitlab-ci.yml)
and if PR passes that's enough

vdk plugins: 

The same as vdk-core goes for each plugin. This means editing each plugin CI file: For example https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-core/plugins/vdk-postgres/.plugin-ci.yml

vdk-control-cli: 
Similarly new CI job "vdk-control-cli-build-with-py310" : 
https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-control-cli/.gitlab-ci.yml


I don't anticipate anything to break. But you never know.
