### ISSUE TITLE
enable locally running control service to be able to connect to a running installation of vdk-server by default 

### ISSUE THREAD

**Issue by mrMoZ1** [vmware/versatile-data-kit#393]
**What is the feature request? What problem does it solve?**

Contributors to this project would find it useful to have a local testing environment that can be started and configured without too much hassle. E.g if a developer has knowledge only on control service they needn't learn how the helm charts and/or vdk-core work to be able to deploy, use (as if installed in cloud) and remove the tool in a local environment.

**Suggested solution**

The current installation of vdk-server comes with a predefined version of the control-service. Ideally, we want to be able to deploy, schedule and run data jobs on a locally running cluster such as vdk server and get the same behavior as if the data job was running in a cloud instance.

Add a feature that enables us to hook a locally running version of the control service (started by a script, or an IDE such as Eclipse or IntelliJ etc..) to a running vdk-server installation. Change the default settings in application.properties to make this connection hassle free and expect the default settings of the vdk-server installed cluster.

**Additional context**

This request was discussed during a team technical alignment meeting and the overall consensus was that this is a worthwhile feature.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
