### ISSUE TITLE
Create env variable that can be used to keep track of vdk execution evnironment - Cloud or Local

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#402]
**What is the feature request? What problem does it solve?**

Currently, we are using the log configuration to determine if the execution is Cloud or Local. We need to refactor this so that we have a dedicated env variable or method in vdk-core and not rely on the logging config.

We should not be using log configuration to determine unrelated concern like where it is executed we may want to add other log configuration types

*Suggested solution**
We can introduce new variable execution environment which can be local or cloud and in control service we would set it to always be cloud.

Alternatively, we can introduce some new method in vdk core and abstract away the logic - in this case it would not be that big of a problem to use log configuration type because it is only one place to change

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
