### ISSUE TITLE
Control Service REST API User documentation with examples

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#411]
**What is the feature request? What problem does it solve?**

Currently we only have a single state diagram and API descriptions https://github.com/vmware/versatile-data-kit/blob/main/projects/control-service/projects/model/apidefs/datajob-api/api.yaml which is not that user friendly.
it is not always clear how it can be used . There are some examples but it would be better if we have use-case specific examples and documentation .

**Suggested solution**
We need to provide more detailed REST API documentation with examples of what can be achieved, it can be in the form of very basic user scenarios or basic wireframes what can be done in UI using the REST API.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
