### ISSUE TITLE
Update REST API State digram to include Execution API

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#412]
**What is the feature request? What problem does it solve?**
We have a diagram that describes the relationships between different API components - https://raw.githubusercontent.com/wiki/vmware/versatile-data-kit/vdk-data-job-lifecycle-state-diagram.png 

The purpose of the diagram is to help users understand better how the API works and how it is expected to be used (describing the usual data engineering work flow) 

It would be good to describe how Execution API fits. If it is too much one diagram we can split it in two.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
