### ISSUE TITLE
Termination Message Writer Plugin should use version of the main distribution of vdk rather than vdk-core version

### ISSUE THREAD

**Issue by mivanov1988** [vmware/versatile-data-kit#419]
**What is the feature request? What problem does it solve?**
Currently the Termination Message Writer plugin writes the vdk-core version to the termination message. We need the version of the main distribution of vdk that aggregates different plugins and vdk-core (e.g quickstart-vdk, company-x-vdk). 
From user point of view, this is the main version they'd be using and they know. Also from the vdk distribution version we can see the version of the plugins potentially.

**Suggested solution**
We can re-use PACKAGE_NAME -
https://github.com/vmware/versatile-data-kit/blob/4cdbe3b0cfedb8ddc675bec27aee4a88389ce16d/projects/vdk-core/src/vdk/internal/builtin_plugins/version/new_version_check_plugin.py#L30
The idea is to set the correct main python package (or distribution) name to use to check for the new version.
But we'd need to fix the description and possibly refactor a bit (so it's not used only for new version check)

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
