### ISSUE TITLE
Support pluggy 1.0

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#428]
Very recently pluggy had release major version : https://pluggy.readthedocs.io/en/stable/changelog.html#pluggy-1-0-0-2021-08-25
 

Pluggy is one of the 2 main libraries we require for vdk-core (other being click) and as it's such a core component it's very important to keep it up to date and support all versions. 
As vdk-core is going to be included in all vdk plugins and all data jobs that means we need to make sure we do not restrict our users in terms. of what they can use. 

That's why it was unpinned initially (the version was not fixed). The major upgrade naturally broke some things and I pinned the version to 0.* . But we need to support 1.0 as well as 0.* ASAP. 

Acceptance Criteria: 

* vdk-core and vdk-control-cli works against all versions of pluggy (0.x or 1.x)

**Comment by gageorgiev** [comment]
This has been implemented. Closing this issue.
https://github.com/vmware/versatile-data-kit/commit/0cd7a3243b90b52562cfda12f8c339cb7068578c
https://github.com/vmware/versatile-data-kit/commit/e16dc5822bb8327c66c1dcbd586491b6311f8bae
