### ISSUE TITLE
Remove Image on deletion of a data job 

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#431]
**What is the feature request? What problem does it solve?**

We should be cleaning up everything after data job is deleted. 

Currently we are leaving the docker images back. This will create a problem down the line as the number of jobs increase or we have often new and deleted job (e.g in tests). 
Still this should be configurable as image may be used for build reproducibility. 

**Suggested solution**
1. Step 1. Add feature flag "remove_container_image_on_job_deletion" in the [helm chart](https://github.com/vmware/versatile-data-kit/tree/main/projects/control-service/projects/helm_charts/pipelines-control-service) and pass it as env variable to control service deployment .
2. Step 2. If the feature flag is true when job is deleted in on job delete, delete all images ?
    2. 1. We probably should add deleteDeployments to [DeploymentService](https://github.com/vmware/versatile-data-kit/blob/main/projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentService.java)
   
 

 
 
 The deletion of image should rely only on OCI Specifications:  https://github.com/opencontainers/distribution-spec/blob/main/spec.md

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
