### ISSUE TITLE
Add API for alert cleanup

### ISSUE THREAD

**Issue by tpalashki** [vmware/versatile-data-kit#441]
**What is the feature request? What problem does it solve?**
The Control Service sends notification emails for completed data job executions. The notifications are based on alerts that are themselves based on metrics exposed by the Control Service for individual data jobs. If a job is disabled, the respective alert remains active forever and this may cause noise in monitoring.

As a Control Service operator, I would like to have an option to reset such alerts manually by using the Control Service's API.

**Suggested solution**
Provide an API to reset alerts for specific jobs.

**Acceptance criteria**
I am able to cancel active alerts by using the API of the Control Service.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
