### ISSUE TITLE
GraphQL API - jobs filtering and sorting at database level

### ISSUE THREAD

**Issue by mivanov1988** [vmware/versatile-data-kit#445]
**What is the feature request? What problem does it solve?**
Currently the API loads all jobs into the memory and then applies filters. This is very inefficient and resource intensive (memory, network traffic, etc.).
If we have 2000 jobs and filter them by team that has 100 jobs, the API will always load 2000 jobs instead of 100 and it will filter them into the memory.

**Suggested solution**
Modify the existing GraphQL data fetcher for executions (com.vmware.taurus.service.graphql.GraphQLDataFetchers) to support database filtering and sorting. The filtering and sorting should be performed at database level for better performance and resource (memory, network traffic, etc.) utilization. The queries should be built dynamically based on the filters.
Sample implementation - https://piotrminkowski.com/2020/07/31/an-advanced-guide-to-graphql-with-spring-boot/

**Acceptance criteria**
The API should perform jobs filtering and sorting at database level.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
