### ISSUE TITLE
Gitlab CI/CD dependencies license check

### ISSUE THREAD

**Issue by ivakoleva** [vmware/versatile-data-kit#45]
Add Licenses whitelist & validation on PR Gitlab check.

* SDK uses https://github.com/raimon49/pip-licenses, that supports `allow-only` verifying licenses match a list of permitted ones.
* Control Service uses https://github.com/jk1/Gradle-License-Report plugin, that supports licenses file (whitelisting) to be verified by task `checkLicense`. 

Find [Dependencies licensing page](https://github.com/vmware/versatile-data-kit/wiki/Dependencies-licensing) on generating dependencies license report (, then cleanup sections after enabling license verification?).
Add a sentence about license check in CONTRIBUTING.md.

**Comment by tozka** [comment]
That looks simple to setup and use https://github.com/marketplace/actions/dependency-review

**Comment by sabadzhiev** [comment]
Triaged. Closed as not relevant.
