### ISSUE TITLE
Remove Unused Job Builder Scripts

### ISSUE THREAD

**Issue by doks5** [vmware/versatile-data-kit#463]
**What is the feature request? What problem does it solve?**
Currently, there are two job builder directories in the Control Service project, one which is used, https://github.com/vmware/versatile-data-kit/tree/main/projects/control-service/projects/job-builder , and another one, which is DEPRECATED, https://github.com/vmware/versatile-data-kit/tree/main/projects/control-service/projects/vdk_job_builder.

This may confuse new contributors, who are not familiar with the project, and lead them to make changes to the wrong directory.

**Suggested solution**
Remove unused job builder directory and scripts.

**Comment by zverulacis** [comment]
The DEPRECATED dir is not found, is this done?
