### ISSUE TITLE
Report proper User Error to users when error is caught by Control Service

### ISSUE THREAD

**Issue by doks5** [vmware/versatile-data-kit#484]
**What is the feature request? What problem does it solve?**
Currently, when a data job fails with an User Error, and the error is caught by the Control Service and not by vdk (e.g., when the k8s pod of the job runs out of memory and is killed), no proper message is reported to users, which makes it difficult for them to understand what has happened.

**Suggested solution**
The addition of proper User Error reporting to the Control Service error handling logic by, e.g., splitting the failed status of k8s pods.

**Additional context**
Discussion here: https://github.com/vmware/versatile-data-kit/pull/479#pullrequestreview-798543281

**Comment by sabadzhiev** [comment]
Triaged. Closed as done.
