### ISSUE TITLE
vdk-core: Error when running built-in version plugin

### ISSUE THREAD

**Issue by ivakoleva** [vmware/versatile-data-kit#513]
**Describe the bug**
HTTP 404 response when running new_version_check_plugin.py check_version() for package name `vdk-core` and package index `pipy.org`

**Steps To Reproduce**
1. Run any vdk-core test in debug
2. Set breakpoint to https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-core/src/vdk/internal/builtin_plugins/version/new_version_check_plugin.py#L65
3. Evaluate `new_package(package_index, package_name).check()`

**Expected behavior**
check() should result in boolean, so no exception is raised, and workflow for printing new version message is not interrupted

**Screenshots**
<img width="1199" alt="Screenshot 2021-11-15 at 16 03 26" src="https://user-images.githubusercontent.com/11415233/141796325-bf3dd361-5dfe-41d7-b99c-065e50c20430.png">

**Version  (please complete the following information):**
 - OS: Mac OS X
 - Version: latest vdk-core

**Additional context**

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
