### ISSUE TITLE
Deploy hidden configuration folders in Data Jobs

### ISSUE THREAD

**Issue by YanaZhivkova** [vmware/versatile-data-kit#517]
**What is the feature request? What problem does it solve?**
A VDK user wants to deploy his .idea folder containing PyCharm configurations with his Data Job. Currently we skip hidden files and folders on deploy and this cannot be done.

**Suggested solution**
Find a way to deploy necessary configuration files and folders which are hidden. Consider this thread while implementing it:
https://stackoverflow.com/questions/43198273/which-files-in-idea-folder-should-be-tracked-by-git

**Acceptance criteria**
If a user has added .idea folder containing necessary PyCharm configurations in his Data Job, deploying the job includes the configurations.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
