### ISSUE TITLE
List available VDK Templates 

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#548]
**What is the feature request? What problem does it solve?**

In order for data engineers to be able to use templates properly they need a way to discover what templates are available in their own installation, see their documentation and accepted parameters. 

See TODO in https://github.com/vmware/versatile-data-kit/blob/bae3652856120ada8d06abe31d5d9aa65993b546/projects/vdk-core/src/vdk/api/job_input.py#L310

**Suggested solution** 
Possibly have a command vdk list-templates ?? 
Or Generate code so that IDE would basically autocomplete `job_input.execute_template(templates.<names popup?>)`

**Comment by sabadzhiev** [comment]
Triaged. We have a similar item in the current VDK roadmap, and will be solved as a separate ticket.
