### ISSUE TITLE
Improve Error classifier logic testing

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#580]
_Originally posted by @tozka in https://github.com/vmware/versatile-data-kit/pull/577#discussion_r758794539_

I think we are missing test cases for error classifying logic :

Possible stack traces (last one is assumed to be the exception)

```
1. vdk.internal
2. job.module
3. vdk.internal (job_input.execute_query for example raises exception)
```
Should be platform error, right? That's already covered by PLATFORM_ERROR_STACKTRACE test

```
1. vdk.internal
2. external library (sqlalchemy, pandas)
3. job.module (called by the external library)
```
This is covered by USER_ERROR_STACKTRACE

```
1. vdk.internal
2. job.module
3. vdk.internal (job_input)
4. external_library
```
Should be platform error . We should add a test. I suspect it will pass.

```
1. vdk.internal
2. job.module
3. vdk.internal (job_input)
4. job.module
```
This is mainly possible in send_xx_for_ingestion as they pass (user provided) iterator which can fail  .
Should be user error.  I suspect the detection won't work.

```
1. vdk.internal
2. job.module
3. vdk.interanl (job_input.ingest)
4. external_library_provided_by_job 
```
Should be user error similar to above but the issue here is harder to detect because we do not know if external_library_provided_by_job is provided by job or by vdk. 

Can you think of other scenarios?

_Originally posted by @tozka in https://github.com/vmware/versatile-data-kit/pull/577#discussion_r758794539_

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
