### ISSUE TITLE
Connection hook spec is not invoked with running queries through CLI

### ISSUE THREAD

**Issue by gageorgiev** [vmware/versatile-data-kit#599]
**Describe the bug**
The connection hook spec - https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-core/src/vdk/api/plugin/connection_hook_spec.py - is not invoked when running queries through a CLI command like `impala-query`.

**Steps To Reproduce**
Include the following code chunk in a plugin file (I used sqlite_plugin.py for testing):
```
@hookimpl
def db_connection_decorate_operation(decoration_cursor):
    op = decoration_cursor.get_managed_operation()
    op.set_operation("SELECT 2")
```
Then, install the plugin and run a data job with a SQL step. Observe that the query was replaced with 'SELECT 2'. Then, run a query using `vdk sqlite-query` and observe that the query has not been replaced.

**Expected behavior**
The connection hook spec should be invoked both when running a data job as well as when running a single query.

**Version  (please complete the following information):**
 - OS: MacOS 11.5
 - Version: latest

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
