### ISSUE TITLE
CI/CD misses dependency conflicts

### ISSUE THREAD

**Issue by doks5** [vmware/versatile-data-kit#771]
**Describe the bug**
As part of https://github.com/vmware/versatile-data-kit/pull/769, the click dependency in vdk-core and vdk-control-cli
was updated to click 8.X. The merge was successfull and no exceptions were raised.

However, the vdk-control-cli's setup.cfg file was missed, and this caused exceptions to be raised when doing new installations (https://github.com/vmware/versatile-data-kit/pull/770).

**Steps To Reproduce**
1. Change version of click in projects/vdk-control-cli/setup.cfg to 7.*
2. Install vdk-core either from PYPI, or by moving into the vdk-core directory and executing `pip install .`
3. Install vdk-control-cli by moving into its directory and executing `pip install .`

**Expected behavior**
The CI/CD pipelines should have caught the dependency conflict.

**Version  (please complete the following information):**
 - OS: All
 - Version  vdk-control-cli 1.2.494451234 depends on click==7.*
                 vdk-core 0.1.494451234 depends on click==8.*

**Additional context**
N/A

**Comment by sabadzhiev** [comment]
Triaged. Closed as we already provided mechanism to catch potential failures.
