### ISSUE TITLE
Make vdk.internal.control.auth.auth.Authentication thread safe 

### ISSUE THREAD

**Issue by vladopp** [vmware/versatile-data-kit#780]
**What is the feature request? What problem does it solve?**
The functionality exposed by Authentication object are useful when implementing plugins that perform asynchronous operations, however in order to use it it must be thread safe so that other usages are not affected.

**Suggested solution**
Add synchronization when reading and writing the underlying file.

**Additional context**

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
