### ISSUE TITLE
Build VDK Executables for the different platforms

### ISSUE THREAD

**Issue by doks5** [vmware/versatile-data-kit#871]
**What is the feature request? What problem does it solve?**
Currently, we face issues when installing Versatile Data Kit on some platforms (e.g., Windows), which creates
poor user experience. Building and releasing (binary) executables for the major platforms, in addition to the PyPI
packages, would allow for the introduction of a one-click installation of vdk, and somewhat better UX.

**Suggested solution**
Maybe use PyInstaller to build executables.

**Additional context**
TBD

**Comment by zverulacis** [comment]
Is this still relevant?

**Comment by sabadzhiev** [comment]
This will be fixed in a later point.
