### ISSUE TITLE
The "Getting started" page seems to be audated

### ISSUE THREAD

**Issue by vecorro** [vmware/versatile-data-kit#888]
**Describe the bug**

**Steps To Reproduce**
> vdk create -n hello-world -t my-team
Path to where sample data job will be created locally [/Users/kike/Dropbox/Experiments/versatile-data-kit]: 
Data Job with name hello-world created locally in /Users/kike/Dropbox/Experiments/versatile-data-kit/hello-world.

> tree
.
└── hello-world
    ├── 10_sql_step.sql
    ├── 20_python_step.py
    ├── README.md
    ├── config.ini
    └── requirements.txt
1 directory, 5 files

**Expected behavior**
The "getting started" guide describes a different behavior. It says:

>hello-world/
├── 10_hello_world.py

Looks like it needs an update.

**Version  (please complete the following information):**
 - OS: macOS 12.4
 - Versatile Data Kit (VDK) Version: 0.3.572339461

**Comment by tozka** [comment]
Hi, Thanks for filing the ticket and the feedback! 

`vdk create` command will create a local job with a sample content (the one you see) . And then the getting started walks through how to change it. But I can see how that is confusing. I have [edited it](https://github.com/vmware/versatile-data-kit/wiki/Getting-Started#edit-data-job) to make it clearer what is happening and easier to follow. I hope that's enough.
