### ISSUE TITLE
Standalone Data Job refactoring (de-duplication) 

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#897]
The code duplication with [this](https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-core/src/vdk/internal/builtin_plugins/run/data_job.py#L255) is something we should fix

_Originally posted by @tozka in https://github.com/vmware/versatile-data-kit/pull/793#pullrequestreview-961666538_

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
