### ISSUE TITLE
Test plugins for breaking changes with other plugins or vdk-core

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#899]
**What is the feature request? What problem does it solve?**

When we release vdk-core we do not test every single plugin that there are not breaking changes because that would be too much. We rely on vdk-core's own regression tests to do so. But in some cases we may miss something. We need a way to validate that plugins are not broken or to find out if they are within 1 day of new vdk-core release

**Suggested solution**
Scheduled jobs that run all plugin's CICD tests. It could do it once a day and automatically opens PRs for plugins that are broken. 

**Additional context**

**Comment by sabadzhiev** [comment]
Triaged. This is already done.
