### ISSUE TITLE
Use latest version of trino in vdk-trino tests

### ISSUE THREAD

**Issue by tozka** [vmware/versatile-data-kit#901]
**Describe the bug**
After https://github.com/trinodb/trino/issues/9129  trino would fail
`drop view if not exists` query if a table with that name exists instead
of silently proceeding.

Which is a problem for us since our tests seem to rely on us they execute
both drop view and drop table to make sure a table or view is deleted.

The tests were fixed in https://github.com/vmware/versatile-data-kit/pull/900 by pinning the version.
But it's good idea to be able to use latest version.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
